### ISSUE TITLE
Alternative UI

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#124]
_From [ysp...@gmail.com](https://code.google.com/u/112893025602567946268/) on February 21, 2010 22:52:58_

Web UI is the thing, which will be very useful for those, who have htpc
with linux on board or just headless home server.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=16_

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on February 23, 2010 18:08:03_

**Labels:** -Type-Defect Type-FeatureRequest

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 24, 2010 09:52:01_

**Summary:** Alternative UI

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 24, 2010 09:52:18_

Issue 240 has been merged into this issue.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 24, 2010 10:32:28_

Issue 238 has been merged into this issue.

**Comment by dhamp** [comment]
_From [sailorvs...@gmail.com](https://code.google.com/u/104386037748133827588/) on August 11, 2010 00:58:20_

+1 I need webui or, at least - separate gtk/qt frontend and backend, that could communicate over tcp/udp

**Comment by dhamp** [comment]
_From [sailorvs...@gmail.com](https://code.google.com/u/104386037748133827588/) on August 11, 2010 01:00:31_

+То же самое по-русски: нужен либо вебгуй, либо возможность связывать морду с бекендом через сеть.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on August 11, 2010 01:09:23_

sailorvspider, а если внимательно посмотреть на транк? Смысл твоих комментов сразу потеряется...

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on September 01, 2010 22:01:58_

На самом деле нужен был безгуевый демон с xml-rpc или чем-то таким.
А уж к нему можно прикручивать чего угодно и сколько угодно :)

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 23, 2010 08:24:24_

Issue 711 has been merged into this issue.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on November 08, 2010 12:58:26_

Issue 817 has been merged into this issue.

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on December 20, 2010 07:16:36_

Issue 899 has been merged into this issue.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on January 29, 2011 04:48:36_

Issue 971 has been merged into this issue.

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on February 05, 2011 10:42:03_

Issue 982 has been merged into this issue.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on February 26, 2011 10:09:53_

Требования к консольной морде:
[20:30:32] \<ONYX> NegatiV: ок, формулирую наиболее ёмко и сжато
[20:56:50] \<ONYX> NegatiV: 
1 Расшаривание с исключениями (простейший способ как в microdc, типа share dir, но с exclude dir)
2 Скачивание (как в microdc - скачать файллист с юзера, войти в него, переходить по директориям и делать get file или get dir, но обязательно с локальным destination(!), типа get file /some/dir - этого очень нехватает в microdc)
3 Раздача
4 Поиск и просмотр результатов поиска (типа как в microdc - search и results)
5 Показ статистики (типа как в microdc status - куда подключен, сколько юзеров на хабе, скольк у тебя скачали, сколько ты скачал, очередь передачи к/от меня)
6 Показ статистики произвольного юзера (ну, доступная инфа по юзеру - описание, почта, клиент email и так далее как обычно)
7 Поис по скачанному файллисту (очень полезно когда знаешь, что искать)
8 Общий чат (достаточно будет say user bla-bla)
9 Приватный чат (достаточно будет say_pub bla-bla)
10 выполнение shell команды из интерфейса

Из возможностей конфигурации - хотелось бы иметь возмоность указать кодировки для хаба, для локальной файловой системы

[20:58:28] \<ONYX> 8 и 9 перепутал содержимое в скобках

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 08, 2011 03:14:00_

**Status:** Accepted  
  **Owner:** dein.negativ  
  **Labels:** -Priority-Medium Priority-High Milestone-Release2.2.2

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 07, 2011 11:51:36_

**Status:** Fixed

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on September 07, 2011 13:34:32_

Преждевременное заявление...

**Status:** Started  
  **Owner:** ---  
  **Labels:** -Priority-High -Milestone-Release2.2.2 Priority-Medium Milestone-Release2.2.4

**Comment by dhamp** [comment]
_From [petro...@gmail.com](https://code.google.com/u/104732113245728650369/) on June 30, 2013 17:27:49_

На сколько я понял, разделение демона и интерфейса завершено.
Установил на headless ubuntu-сервере демона. Запустил на маке в той же сети EiskaltDC++ 2.2.8 но никак не могу понять как подключиться к демону.
Помогите нубу...

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on July 01, 2013 09:05:17_

Как я уже ответил в письме:

\>  можно ли сейчас использовать демон EiskaltDC++ на сервере, и клиента с
\>  интерфейсом подключенным к этому демону на локальном компе?

Да.

\>  А то, вроде как демон есть отдельный, и не могу понять где взять к нему
\>  интерфейс.

В настоящий момент к демону есть только интерфейс командной строки (CLI).
Подробности можно посмотреть здесь: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.2.8/ChangeLog_ru.txt https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.2.8/eiskaltdcpp-cli/TODO >  На Маке последний dmg с программой не содержит меню типа "Подключиться к
\>  серверу по адресу ...".

Полноценный графический интерфейс на Qt не использует демон и никогда не будет: http://tehnick-8.narod.ru/eiskaltdcpp/faq.html В бандле под мак отсутствует eiskaltdcpp-cli-jsonrpc. Если он нужен, то можно
взять прямо из исходников: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.2.8/eiskaltdcpp-cli/cli-jsonrpc.pl https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.2.8/eiskaltdcpp-cli/cli-jsonrpc-config.pl Это perl-скрипт и для его работы в системе должен быть установлен
интерпретатор Perl и соответствующие модули: https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.2.8/eiskaltdcpp-cli/README_ru >  Или, может, уже есть WebUI?

У нас --- нет. Но я слышал, что кто-то делал для своих специфических нужд.
Именно для этого в демоне реализовано управление по JSON-RPC и XML-RPC:
любой клепатель сайтов сможет без труда прикрутить его поддержку.

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
