### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#125]
_From [Nickollai](https://code.google.com/u/Nickollai/) on March 23, 2010 16:31:21_

Предлагаю их сообщать в этот баг.

1) на иконке в лотке: "Show/hide window"
2) в настройках: "I'm away. State your business and I might answer later if
you're lucky."

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=237_

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on March 23, 2010 09:23:20_

3) на иконке в лотке: "Exit"

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on March 23, 2010 15:14:14_

1) и 3) --- r437 2) Исправлено не будет. Это сообщение указано по дефолту в ядре. 
Менять его там смысла нет. Пользователи все равно изменят в настройках 
на свой вариант.

Ветку закрывать не буду. Пишите и дальше по теме сюда.

**Status:** Started  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 26, 2010 10:50:41_

**Labels:** -Priority-Medium Priority-Low

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 02, 2010 05:56:03_

**Summary:** Translation issues

**Comment by dhamp** [comment]
_From [yEhe...@gmail.com](https://code.google.com/u/111988753636400384292/) on April 06, 2010 04:14:02_

Все сообщения от ядра в строке статуса. К примеру, сообщения прогресса хеширования.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 06, 2010 04:36:51_

Сообщения ядра было решено не переводить.

**Comment by dhamp** [comment]
_From [yEhe...@gmail.com](https://code.google.com/u/111988753636400384292/) on April 06, 2010 12:54:01_

Хм. Пользователь их видит. Почему решили не переводить? 8)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 12, 2010 15:49:46_

При наведении на ник в списке пользователей появляется tooltip с подробной инфой.
Так, если навести на оператора, то:
Роль на хабе: Operator

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on April 17, 2010 04:41:15_

Всплывающая подсказка для значка на тулбаре отвечающего за поиск в чате -
"Поиск/Фильтр": это только поиск, свойств фильтра как, например, в файл-листе он не
имеет.(к выделению всех найденных фрагментов текста - слово фильтр как то не очень
подходит)

Может лучше отображать в всплывающих подсказках для значков работы с чатом тот же
текст что и у соответствующих пунктов меню по пкм в чате?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 17, 2010 04:47:03_

pavelvat, нет не лучше. Так просто и понятно. Одна кнопка для всех 
схожих действий в разных виждетах и одно название.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 17, 2010 04:50:10_

"Поиск/Фильтр" значит что эта кнопка открывает для виджетов либо поле ввода для
фильтрации, либо текстового поиска. Что конкретно происходит в виджете эту кнопку не
интересует.

**Comment by dhamp** [comment]
_From [akos.be...@gmail.com](https://code.google.com/u/117390716465361621707/) on April 18, 2010 05:24:33_

Hi.

Someone can explain for me exactly two options from fasthash dialog?
1: No reserve
2: Private page mapping
What is it?
Thanks

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 18, 2010 05:33:16_

akos.berki,
1: Do not reserve swap space for this mapping. When swap space is reserved, one has
the guarantee that it is possible to modify the mapping. When swap space is not
reserved one might get SIGSEGV upon a write if no physical memory is available. See
also the discussion of the file /proc/sys/vm/overcommit_memory in proc(5). In kernels
before 2.6, this flag only had effect for private writable mappings. 
2: Create a private copy-on-write mapping. Stores to the region do not affect the
original file. It is unspecified whether changes made to the file after the mmap()
call are visible in the mapped region.

Populate: Populate (prefault) page tables for a file mapping, by performing
read-ahead on the file. Later accesses to the mapping will not be bocked by page faults.

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on April 19, 2010 02:29:28_

Настройки -> Подключения -> Ограничения:
"Другая скорость загрузки в часы от" -> "Другая скорость в часы от"

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on April 19, 2010 05:05:46_

\>Настройки -> Подключения -> Ограничения:
"Другая скорость загрузки в часы от" -> "Другая скорость в часы от"

Извиняюсь, ошибся - это я на старой ревизии проверял.

**Comment by dhamp** [comment]
_From [husumo](https://code.google.com/u/husumo/) on April 30, 2010 11:18:24_

Hi. We can get one more svn release before text freeze? Thx.

**Comment by dhamp** [comment]
_From [husumo](https://code.google.com/u/husumo/) on April 30, 2010 11:19:33_

Sorry, i mean one more build package from svn.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 30, 2010 11:31:50_

husumo,
For Ubuntu/Fedora/etc?

**Comment by dhamp** [comment]
_From [husumo](https://code.google.com/u/husumo/) on April 30, 2010 13:47:57_

yes, i use ubuntu btw.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 30, 2010 13:56:59_

Here is some problems on Launchpad after Ubuntu 10.04 release, so build starts in
15-16 hours.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on May 20, 2010 10:33:58_

**Labels:** -Type-Enhancement Type-DevProcess

**Comment by dhamp** [comment]
_From [yEhe...@gmail.com](https://code.google.com/u/111988753636400384292/) on May 20, 2010 12:45:42_

Было бы нелохо оставлять переводчикам для перевода полные предложения.
То есть, к примеру, вместо « joins the chat», которое в программе выглядит как
«nickname joins the chat», оставлять для перевода «%1 joins the chat». Таким образом
у переводчиков будет возможность изменить порядок слов в предложении, что иногда оч.
кстати.

**Comment by dhamp** [comment]
_From [yEhe...@gmail.com](https://code.google.com/u/111988753636400384292/) on June 21, 2010 08:26:08_

Favorite Hubs > ПКМ по хабу > Change:
Название диалога — "Dialog", хотя должно быть что-то более информативное, типа "Properties".
Всплывающая подсказка для поля "Description" повторяет подсказку для поля "User description": "This description will show in the user list." Нужно или убрать подсказку для "Description", или изменить её: "This description will show in Favorite Hubs window."

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on August 10, 2010 04:24:42_

Issue 636 has been merged into this issue.

**Comment by dhamp** [comment]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 20, 2010 20:58:49_

Заголовок окна выбора смайлов Select Smile

**Comment by dhamp** [comment]
_From [i.Kliok@gmail.com](https://code.google.com/u/i.Kliok@gmail.com/) on November 09, 2010 05:09:25_

Gtk-интерфейс.
1. Не переводятся пункты контекстного меню вкладки Favorite hubs («_Add», «C_onnect», «_Properties», «_Remove»).
2. Не переводится название вкладки «ADL Search» и названия столбцов в этой вкладке («Enabled», «Searsch string», «Source Type», «Destination Directory», «Min Size», «Max Size»).
3. Не переводятся названия кнопок «Up», «Down», «Add», «Remove», «ok», «Apply».
4. Не переводятся названия кнопок диалогов «Ok», «Cancel», кнопки «ok» интерфейса.
5. Вкладка «Preferences» — «Download» — «Download to»: не переводятся названия столбцов «Favorite Name» и «Directory».
6. Вкладка «Shared directories» настроек: не переводятся названия столбцов «Virtual name», «Directory», «Size».
7. Вкладка «Advanced» — «User commands»: не переводятся названия столбцов «Name», «Hub», «Command».
8. Вкладка «Personal Information», список кодировок: не переводится строка «System default».
9. Не переводится название столбца «IP» в списке передач, «TTH» в списке файлов.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 21, 2010 09:24:22_

i.Kliok, проверь сейчас. Заодно перевод обновишь...

**Comment by dhamp** [comment]
_From [i.Kliok@gmail.com](https://code.google.com/u/i.Kliok@gmail.com/) on November 23, 2010 02:35:29_

tehnick.alive, обновил перевод, проверил все пункты: как не переводилось, так и не переводится. %)
Подумал, что, может, что-то не так с файлами перевода на белорусский, подменил их на русский перевод — та же ерунда, те же непереводимые пункты.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 28, 2010 06:28:41_

1. http://img94.imageshack.us/img94/7553/desktop298.png Более того, эти строки отсутствют в исходниках:
$ grep -r 'C_onnect' eiskaltdcpp-gtk/
Сравни с:
$ grep -r 'Connect' eiskaltdcpp-gtk/ 
3. http://img408.imageshack.us/img408/4329/desktop299.png 4. Скорее всего это связано с глобальными настройками используемой gtk-темы.
У меня так: http://img221.imageshack.us/img221/2289/desktop300.png 2, 5, 6, 7. Поправлю.
8. Вообще-то это было сделано специально. Но можно и исправить.
9. А это нужно вообще?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 28, 2010 06:29:29_

**Owner:** tehnick.alive

**Comment by dhamp** [comment]
_From [i.Kliok@gmail.com](https://code.google.com/u/i.Kliok@gmail.com/) on November 28, 2010 07:37:07_

3. Уточню. Не переводятся названия некоторых кнопок.
3.1. «Add», «Remove» — в настройках «Download» — «Download to». http://img833.imageshack.us/img833/7255/screenshotjc.png 3.2. «Add», «Remove», «Apply» — в настройках «Download» — «Preview». http://img148.imageshack.us/img148/3128/screenshot1m.png 3.3. «Add», «Remove» — в настройках «Share». http://img694.imageshack.us/img694/5476/screenshot2d0.png 3.4. «ok» — в настройках «Appearance» — «Notification». http://img522.imageshack.us/img522/7787/screenshot3d.png 3.5. «Add», «Edit», «Up», «Down», «Remove» — в настройках «Advanced» — «User commands». http://img24.imageshack.us/img24/1316/screenshot4ol.png Хотя вот в том же окне ADL Search подобные кнопки (и пункты контекстного меню) переведены.
Впрочем, я так понимаю, что у меня, на Debian testing, просто общесистемная локализация отстаёт от изменений в интерфейсе, а Gtk-морда иногда берёт названия из этой самой «общей» локализации. %) А иногда — в окне ADL Search, к примеру, — морда пользуется своими ресурсами. ;)
4. Вот, честно говоря, кнопку «ok» — именно маленькими буквами первый раз вижу в интерфейсе. :)
8. Всё-таки хорошо было бы исправить. Хотя бы потому, что в Qt-морде это строчка таки переводится. (Не совсем понятно: зачем эту строчку в GTK-морде оставили непереведённой?)
9. Нужно, да. "TTH" совершенно не обязательно переводится как "TTH" — как и "IP". :)
(Это, наверное, общий принцип должен быть: весь текст, который видит пользователь, должен быть доступен для перевода.)

Вот ещё:
10. В выводе Qt-морды на консоль остаются непереведёнными, хотя в .ts файле перевод наличествует, строчки:
 а) «Signal handlers installed.»
 б) «Quit...»,
 в) «Loading: ».
Кроме этого, в .ts файле нет строчки «Internal server running on %s», которая появляется в том же выводе на консоль при запуске Qt-морды: «Internal server running on 4212».

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on January 04, 2011 02:03:37_

Первая вкладка окна "Об EiskaltDC++" с некоторых пор потеряла свой перевод и всегда отображается на английском.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on January 08, 2011 09:23:27_

pavelvat, это связано с issue #920 . После следующего обновления файлов перевода все будет нормально...

**Comment by dhamp** [comment]
_From [despic...@gmail.com](https://code.google.com/u/116337100048966912579/) on March 09, 2011 11:32:14_

Gtk-интерфейс: 2.2.1
Панель инструментов:
Подсказка на кнопке "Посмотреть файлы", открывает вкладку "Очередь загрузок". При первом опыте с  EiskaltDC++ по новым кнопкам с такими подсказками не сразу нашел "Очередь загрузок". В Linuxdcpp по английски легче разобраться: "View the files to be downloaded"

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on November 20, 2011 03:54:49_

смотри скрин

**Attachment:** [screen1.png](http://code.google.com/p/eiskaltdc/issues/detail?id=237#hc36)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 20, 2011 06:03:08_

pavelvat, спасибо, поправил.

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
