### ISSUE TITLE
Пользовательские скрипты

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#126]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 04, 2010 17:58:16_

В этот issue предлагаю кидать ссылки на качественные пользовательские 
скрипты, которые можно использовать командой /sh в нашем клиенте.

Требования к скриптам:
1) Сверху шапка с указанием копирайта и лицензии. Предпочтительная 
лицензия: GPLv3 и выше.
2) Краткое описание и/или пример аутпута.
3) Собственно код.

Хорошие скрипты будут добавлены в проект (каталог 
./eiskaltdcpp/examples/), а после установки они будут доступны в каталоге 
программы, например: /usr/share/eiskaltdcpp/examples/

Первым претендентом на добавление, является скрипт от пользователя 
nS.microsoft: http://pastebin.com/wrP4hZUt Его желательно дополнить: см. 
пункт 2. Название же тоже полезно давать разумное. В данной случае 
можно назвать его: xmms2_audacious2.ru_RU.UTF-8.php

Жду одобрения от dein.negativ перед добавлением.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=344_

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on April 04, 2010 07:14:29_

1)лицензия: нету, распространение и модификация не преследуются :)
2)что делает: показывает что сейчас играется в mpd
зависимости: bash, mpc, mpd
пример вывода в консоль: /me listening now Blind Guardian - The Bard's Song: In The
Forest
пример вывода в чат eiskaltdcpp: [17:45:03] * dhampire listening now Blind Guardian -
The Quest For Tanelorn
3) 
\#!/bin/sh
mpc=$(mpc --format "%artist% - %title%" | head -n 1)
echo "/me listening now $mpc"

нужность: авось кому-нибудь пригодится :)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 04, 2010 10:52:33_

Без лицензии никак нельзя. В крупных проектах это не поймут. Например, 
в Дебиане. А подобный скрипт можно вполне под Public Domain пихнуть... 
=)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 04, 2010 15:34:53_

Блин, назвал тему так же как и я. Читая updates list я даже запутался :)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 04, 2010 16:55:52_

eiskaltdcpp-svn.x86_64: W: wrong-script-end-of-line-encoding
/usr/share/eiskaltdcpp/examples/xmms2_audacious2.ru_RU.UTF-8.php
This script has wrong end-of-line encoding, usually caused by creation or
modification on a non-Unix system. It will prevent its execution.

**Comment by dhamp** [comment]
_From [unreal7...@gmail.com](https://code.google.com/u/109137478181396762966/) on April 04, 2010 17:04:14_

Вова, не матюгайся,мысли у линуксоидов сходятцо)
собственно выполняю просьбу товарища tehnick
голова у нас с камрадом egikpetrov работала одинаково, скрипты впринципе идентичные))
скрины к сожалению вечером только закину, когда доберусь до компа домашнего.

1)лицензия: Public Domain
2)что делает: вывод информации о проигрываемом треке из ритмбокса/аудасиоса в чат
пример вывода в консоль: 
/me Rhythmbox playing now: Rammstein - Sonne
/me Audacious playing now: Rammstein - Sonne
Forest
пример вывода в чат eiskaltdcpp:
[10:57:01] * Ben_Vladen Rhythmbox playing now: Rammstein - Sonne
[10:57:03] * Ben_Vladen Audacious playing now: Rammstein - Sonne
3) Код
_______________________________________
\#!/bin/bash
rh=$(rhythmbox-client --print-playing)
echo /me Rhythmbox playing now: $rh
exit
_______________________________________
\#!/bin/bash
au=$(audtool2 --current-song)
echo /me Audacious playing now: $au
exit
_______________________________________

в ритмбоксе можно дополнительно параметры прописать,в мане есть описалка.

**Comment by dhamp** [comment]
_From [vasilisc777](https://code.google.com/u/vasilisc777/) on April 04, 2010 19:54:59_

а насчет МузыкальногоСкрипта
нельзя его сделать понимающим популярные проигрыватели и выводящим из запущеного
проигрывателя текущий трек?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 05, 2010 00:01:08_

vasilisc777, ты внимательно посмотри скрипты из issue. Они здесь все "музыкальные"...

**Comment by dhamp** [comment]
_From [nuk...@gmail.com](https://code.google.com/u/106356693037185056334/) on April 05, 2010 00:41:19_

Вы издеваетесь? eiskaltdcpp теперь будет похапэ тянуть?

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 05, 2010 01:08:01_

Эти скрипты не от балды в "examples"
Примеры. Хочешь юзай, хочешь нет.
php никто ставить не заставляет :)

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on April 05, 2010 04:06:21_

\>Вы издеваетесь? eiskaltdcpp теперь будет похапэ тянуть?
ну конечно же не только php, ещё apache,mysql,perl и конечно же сервер в придачу ^_^.

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 05, 2010 04:22:56_

Видеокарту для хеширования :-D

**Comment by dhamp** [comment]
_From [nS.micro...@gmail.com](https://code.google.com/u/114430502993187783008/) on April 05, 2010 07:15:00_

\> Его желательно дополнить: см. пункт 2.
Требования: php4+
Вызов: script_name [audacious2|xmms2]
Поддержка xmms2 писалась для версии 0.5 еще под Valknut, может не работать сейчас.
Пример вывода радио:
отрывается под WINTER, MARKUS - Electro Love Song @ recordradio.spb.ru |
\<192kbps:44.1kHz> Радио: Record 192k MP3 | Адрес: http://radio.san.ru:8000/record [Powered by Audacious 2.3-beta3 | GNU/Linux]

Локальный файл:
отрывается под Madonna - The Power of Good-Bye; Длина песни: 4:12; Уже прослушал: 2%
| \<320kbps:44.1kHz> [Powered by Audacious 2.3-beta3 | GNU/Linux]

**Comment by dhamp** [comment]
_From [zavl...@gmail.com](https://code.google.com/u/108048131263273628312/) on April 07, 2010 04:35:59_

А для qmmp нет ни у кого скрипта? 
Все-таки единственная прога, всегда корректно работающая с cue файлами и их
кодировками, и при этом поддерживающая шкуры винампа. Так что думаю, много людей ею
пользуется

**Comment by dhamp** [comment]
_From [alak...@gmail.com](https://code.google.com/u/117554560115298556961/) on April 07, 2010 07:55:42_

Как бы прикрутить нужный скрипт к отдельной кнопке "сейчас играет". А то каждый раз
писать в чате подобное: 
/sh /usr/share/eiskaltdcpp/examples/rhythmbox.en_US.sh
малоприятное удовольствие.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 07, 2010 08:01:51_

alakorn,
а использовать команду /alias?

**Comment by dhamp** [comment]
_From [alak...@gmail.com](https://code.google.com/u/117554560115298556961/) on April 07, 2010 08:18:54_

dein.negativ
Можно поподробнее, как ей пользоваться?
Насколько понимаю, прикрутить гуй (кнопку) данная команда не поможет, а лишь позволит
сократить мою команду  /sh /usr/share/eiskaltdcpp/examples/rhythmbox.en_US.sh 
до более короткой, например, /play

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on April 07, 2010 08:29:59_

/alias play::/sh /usr/share/eiskaltdcpp/examples/rhythmbox.en_US.sh

так сложно прочесть man или вывод команды /help ?

**Comment by dhamp** [comment]
_From [alak...@gmail.com](https://code.google.com/u/117554560115298556961/) on April 07, 2010 08:34:49_

Спасибо, уже успел разобраться сам )

**Comment by dhamp** [comment]
_From [unreal7...@gmail.com](https://code.google.com/u/109137478181396762966/) on April 07, 2010 15:53:05_

Небольшое дополнение по скрипту товарища nS.microsoft, применительно к убунте:
у кого не срабатывает скрипт, и ругается что нет файла-или каталога /usr/bin/php, то 
установить пакет php5-cli, и подредактировать скрипт(заменить #!/usr/bin/php на #!/
usr/bin/php5)
З.Ы. скрипт кошерный, спасибо автору)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 07, 2010 16:40:05_

А разве пакет в убунте при установке симлинк на бинарник не создает? В дебиане все 
нормально с /usr/bin/php

Кстати, этот автор не так давно вот такую вещь собирался замутить: https://code.google.com/p/dcphp/ Только мне не понятно, что бы это было в конечном итоге по его замыслу.

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 07, 2010 17:16:51_

Симлинк симлинком, но у меня сусевый пакет со скриптами при установки рушается на
неудовлетворенную зависимость, мол ничто не предоставляет /usr/bin/php

**Comment by dhamp** [comment]
_From [unreal7...@gmail.com](https://code.google.com/u/109137478181396762966/) on April 07, 2010 17:33:11_

а нифига, пхп5 и все, а в случае с пхп4 вроде как создаёт

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 08, 2010 00:46:13_

Решил я значит сам поразмять пальцы.
Представляю на ваш суд свое поделие.

Скрип поддерживает более 5 плееров и имеет пользовательский конфиг.

Тут же небольшой фичреквест (для хранения конфига)
Было бы неплохо, чтоб eiskaltdcpp при запуске скриптов помещал в ENV переменную с
указанием до пути к директории конфигов.

**Attachment:** [mpris_now_playing.sh](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc23)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on May 12, 2010 23:44:57_

uni211, прочитай начало issue. И дополни информацию о скрипте.

**Comment by dhamp** [comment]
_From [uni...@gmail.com](https://code.google.com/u/101178445204139973213/) on May 12, 2010 23:57:51_

1) Public Domain

2) Выводит песню играющую в qmmp. Должен быть включен модуль MPRIS в qmmp.
[13:53:44] *  ** visual слушает Orjan Nilsen - So Long Radio

3)
\#!/bin/sh
export DISPLAY=:0
MESSAGE=""
NOWPLAYING=`qdbus org.mpris.qmmp /Player org.freedesktop.MediaPlayer.GetMetadata`
if [ $? = 0 ] && [ -n "$NOWPLAYING" ]; then
ARTIST=`echo "$NOWPLAYING" | sed -ne 's/^artist: \(.*\)$/\1/p'`
TRACK=`echo "$NOWPLAYING" | sed -ne 's/^title: \(.*\)$/\1/p'`
MESSAGE="слушает $ARTIST - $TRACK"
fi

echo -e "/me $MESSAGE"

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on May 13, 2010 16:11:08_

Обновление скрипта mpris_now_playing.sh
Добавлена поддержка трех плееров. Теперь общее число плееров: 10
Добавлена поддержка вывода магнетов.

P.S. И не забудьте удалить/отредактировать старый конфиг ;-)

**Attachment:** [mpris_now_playing.sh](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc27)

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on May 20, 2010 10:33:37_

**Labels:** -Type-Other Type-DevProcess

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 08, 2010 06:42:40_

Я пользуюсь стандартными проигрывателями "Rhythmbox" и "Totem" в Ubuntu(GNOME)

$ sudo apt-get install php5 php5-cli && sudo nano /usr/share/eiskaltdcpp/commands

Вставляете скриптик что скачали, после:
$ sudo chmod +x /usr/share/eiskaltdcpp/commands
и вместо {username} указываете вашу учётную запись
$ sudo chown {username} /usr/share/eiskaltdcpp/command

/alias p::/sh /usr/share/eiskaltdcpp/commands
/alias u::/sh /usr/share/eiskaltdcpp/commands uptime
/alias b::/sh /usr/share/eiskaltdcpp/commands black
/alias r::/sh /usr/share/eiskaltdcpp/commands ratio
/alias ps::/sh /usr/share/eiskaltdcpp/commands process
/alias t::/sh /usr/share/eiskaltdcpp/commands torrent
/alias pn::/sh /usr/share/eiskaltdcpp/commands ping
/alias ip::/sh /usr/share/eiskaltdcpp/commands ip

вызовы:
/p - то что играет в rhythmbox или в totem
/u - ваш uptime
/b - ваш черный список
/r - ваше соотношение
/t - ваше соотношение в торрент клиенте
/ps - системная информация
/pn - пингуем сайт mail.ru
/ip - ваш ip адрес

**Attachment:** [commands.php](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc30)

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 08, 2010 06:45:16_

Авторам EiskaltDC++ огромнейшее спасибо за столь приятный клиент ;-)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 08, 2010 08:26:42_

gotlium, добавил в r1161 с небольшими изменениями.
Лично я считаю выдаваемую этим скриптом информацию бесполезной.
Но пусть будет. Мб кто-то даже будет использовать...
PS: обилие смайлов позабавило. =)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 08, 2010 08:30:02_

gotlium, уточни, какую именно лицензию и какой версии ты имел в виду, давая ссылку: http://www.opensource.org/licenses/gpl-license.php

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 08, 2010 08:47:43_

The GNU General Public License (GPL)
Version 2, June 1991

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 08, 2010 13:05:16_

tehnick.alive, подлатал немного скрипт.
поддерживаемые проигрыватели:
видео: totem, smplayer, vlc, gnome-mplayer, xine
аудио: rhythmbox, audacious2, amarok
так же указал лицензию.

**Attachment:** [commands.php](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc35)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 08, 2010 14:22:05_

gotlium, ты слегка опоздал: EiskaltDC++ 2.0.3 уже релизнулся... Скрипт обновил ( r1168 ) со своими правками.

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 08, 2010 22:28:08_

отчего не работает консоль JavaScript и Amarock в Gnome?

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on June 09, 2010 04:15:00_

\>отчего не работает консоль JavaScript и Amarock в Gnome?
отчего бы вам не создать по этому поводу issue, где вы доступно опишите чего у вас не работает?

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 09, 2010 05:08:36_

потому как это касается пользовательских скриптов:) от того и задал тут:) особо описывать нечего. Ubuntu 9.04 Gnome.EiskaltDC++ 2.0.4 версия как бы нестабильная. но только на слово "нестабильная" упор делать не нужно. раз это есть, значит это тестировалось и проверялось. Просто возможно у меня не поставлено каких-то пакетов kde, которые использовал автор.
Ну и соответственно вкладка "Инструменты" - "Консоль JavaScript" + "Управление скриптами". При работе с ними, предполагаемых действий не выполняется, после появления иконок в Toolbar-e так же. Не тех что шли с пакетом, не те что писал сам.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on June 09, 2010 05:11:14_

gotlium,
qtscriptgenerator установлен?

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 09, 2010 05:31:05_

В штатном репозитарии данного пакета я не нашел!
Как я понял libqtscript4. Но это не помогло!

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 09, 2010 06:31:29_

gotlium, все пакеты, которые рекомендует eiskaltdcpp-unstable установлены?
Recommends: libqtscript4-core, libqtscript4-gui, libqtscript4-network, libqtscript4-xml

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 09, 2010 06:35:11_

\>потому как это касается пользовательских скриптов:)

Здесь обсуждаются совсем другие пользовательские скрипты.
Про QtScript была отдельная ветка, но ее уже закрыли, так что лучше создать новую.

**Comment by dhamp** [comment]
_From [gotlium](https://code.google.com/u/gotlium/) on June 10, 2010 03:43:11_

Не знаю отчего, но на 10.04 всё работает. Это и удивительно. И при этом я не устанавливал ничего из того что рекомендовалось! В целом сделал по аналогии.

**Attachment:** [gnome.tar.gz](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc44)

**Comment by dhamp** [comment]
_From [Nickollai](https://code.google.com/u/Nickollai/) on June 11, 2010 16:06:51_

Подправил sh скрипты, советую читать http://mywiki.wooledge.org/BashGuide

**Attachment:** [0001-fixed-sh-scripts.patch](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc45)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 12, 2010 14:12:10_

Nickollai, r1200

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 12, 2010 14:22:32_

gotlium, r1201

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on August 23, 2010 17:57:00_

Патч устраняет проблемы с путями, в которых встречаются пробелы.

**Attachment:** [mpris_now_playing.en_US.patch](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc48)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on September 01, 2010 22:00:22_

Новая версия патча решает на корню проблему с файлами, путь к которым возвращается в url кодированном виде.

**Attachment:** [mpris_now_playing.en_US.patch](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc49)

**Comment by dhamp** [comment]
_From [mon...@mail.ru](https://code.google.com/u/112206820262747877057/) on November 25, 2010 01:44:00_

а можно сделать сделать скрипт типа черного списка по именам чтоб не качал с меня???

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 25, 2010 03:43:05_

mont86@mail.ru, чем не устраивает существующий фильтр по IP? Это надежней, т.к. ник обычно легко можно сменить...

**Comment by dhamp** [comment]
_From [DjPavlus...@gmail.com](https://code.google.com/u/101451910502142024965/) on April 07, 2011 07:45:00_

А можно сделать скрипт для foobnix?
Попробовал переделать https://code.google.com/p/eiskaltdc/source/detail?r=1168 в итоге выводится название трека только для одной песни из всех. Неважно, в свернутом или развернутом виде.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on June 11, 2011 00:44:16_

Issue 1090 has been merged into this issue.

**Comment by dhamp** [comment]
_From [snegovik...@gmail.com](https://code.google.com/u/101284576011756847495/) on August 07, 2011 16:50:25_

А есть возможность сделать скрипт который будет отсылать через промежуток времени сообщение в чат?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on August 07, 2011 22:37:09_

snegoviktlt,
1) Можно на яваскрипте: https://code.google.com/p/eiskaltdc/wiki/Scripting 2) Можно на Lua. Теоретически... (Я не пробовал)

PS: за спам банят...

**Comment by dhamp** [comment]
_From [snegovik...@gmail.com](https://code.google.com/u/101284576011756847495/) on August 09, 2011 07:10:37_

так как такой скрипт сделать? и как запустить lua скрипты?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on August 10, 2011 05:53:30_

Примеры скриптов смотри в исходниках.
1) Подкаталог eiskaltdcpp-qt/qtscripts/
2) Подкаталог luascripts/

Запускаются они по разному.
1) Можешь, например, добавить кнопку на панель инструментов.
2) Специальной командой в чате любого хаба. См. подсказку /help там же...

**Comment by dhamp** [comment]
_From [snegovik...@gmail.com](https://code.google.com/u/101284576011756847495/) on August 10, 2011 07:08:50_

а как можно понять запустился lua скрипт или нет?

**Comment by dhamp** [comment]
_From [i.n.stre...@gmail.com](https://code.google.com/u/112958030129815107214/) on September 22, 2011 04:08:15_

Скажите, пожалуйста, возможно ли использовать скрипты для вывода названия проигрываемого медиа-файла в Windows?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on September 22, 2011 06:02:06_

Использовать можно. Только готовых примеров нет. И не все аудиопроигрыватели под виндой позволяют получить от них информацию...

**Comment by dhamp** [comment]
_From [i.n.stre...@gmail.com](https://code.google.com/u/112958030129815107214/) on September 23, 2011 08:09:01_

Ну, порядочное большинство. И всё-таки, как сделать? Расскажи хотя бы на 1-м примере, дальше сделаю по аналогии. [secretcode]ff[/secretcode]

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on September 23, 2011 09:41:57_

уточню.
не все проигрыватели позволяют получить от них информацию без задействования подобного http://bazaar.launchpad.net/~bcdcpp-team/dcplusplus/bcdcpp/view/head:/win32/Winamp.h проигрывателе-/платформо-зависимого кода, писать(да фиг с ним - "копипастить" :}) и поддерживать который у нас просто некому, разработчиков под win32 среди нас нет.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on September 23, 2011 14:04:10_

Ну, вообще-то есть pavelvat. И если он захочет, то сможет в ./win32 отдельную утилиту для винампа запилить, например. Айскальту-то все равно, скрипт запускать или бинарник...

**Comment by dhamp** [comment]
_From [i.n.stre...@gmail.com](https://code.google.com/u/112958030129815107214/) on September 25, 2011 04:44:11_

Разработчики должны быть, ведь я как-то сижу под виндой в клиенте?) 
Что в общих словах нужно сделать, чтобы всё работало? Достаточно по команде в чате, с кнопкой фиг с ней.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 25, 2011 05:39:59_

Никто специально под Windows ничего не пишет - просто код пишется так чтобы он работал на многих платформах без необходимости поддержки каждой платформы в отдельности.

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on September 25, 2011 06:41:28_

Лично у меня нет никакого желания добавлять поддержку для какого-то там проприетарного winamp, тем более тем способом который озвучил egikpetrov.
Уж если это когда-нибудь и будет добавлено то только в виде скрипта.

В "Инструменты->Управление скриптами" на данный момент уже есть поддержка скриптов для Now PLaying, причём два плеера - Clementine и Amarok существуют и под Windows, но проблема в том что они написаны не кроссплатформенным способом, например в скрипте для Clementine используется скрипт для bash:
function actionClicked(){
  var shell = new ShellCommandRunner(SCRIPTS_PATH+"clementine_nowplay/clementine.sh")
  shell["finished(bool,QString)"].connect(shellDone);

  shell.run();
}

В итоге из существующих на данный момент скриптов кроссплатформенными являются только два - это LogManager Widget(на QtScript) и Tic-Tac-Toe(на QML).

В то же время информацию о проигрываемой композиции совершенно точно можно получить от плеера Clementine и под Windows - например Windows сборка Jabber-клиента Psi+ https://code.google.com/p/psi-dev/ показывает эту информацию, так что можно посмотреть как сделано у них, и написать новый кроссплатформенный скрипт для Clementine. Инструкции как писать скрипты на QtScript можно найти тут: https://code.google.com/p/eiskaltdc/wiki/Scripting

**Comment by dhamp** [comment]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on October 10, 2011 11:14:46_

\>В то же время информацию о проигрываемой композиции совершенно точно можно получить от плеера Clementine и под Windows - например Windows сборка Jabber-клиента Psi+ https://code.google.com/p/psi-dev/ показывает эту информацию

С этим я серьёзно ошибся - оказалось что аккаунт на сервере jabber.ru хранит информацию о проигрываемой композиции если соответствующая настройка включена в Psi+. Так вот, я просто слушал один и тот же альбом под Linux и под Windows, в итоге информация о текущей композиции сохранилась в моём аккаунте на сервере jabber.ru и после перезагрузки в Windows начала отображаться в ростере. Я слушал под Windows тот же альбом и композиция совпала с той что была под Linux - отсюда и ошибка. В ростере клиента Psi+ продолжает всегда отображаться одна и та же композиция - та которая была под Linux на момент выхода.

**Comment by dhamp** [comment]
_From [unreal7...@gmail.com](https://code.google.com/u/109137478181396762966/) on February 10, 2012 11:59:04_

Очередной простейший музыкальный скриптик, для популярного плейера DeaDBeeF
1)лицензия: Public Domain
2)что делает: вывод информации о проигрываемом треке из DeaDBeeF и магнет-ссылки на файл в чат
пример вывода в консоль: 
/me DeaDBeeF playing now:Black Heaven - Himmel ohne Sterne, длина песни 3:59, уже прослушал 2:38 ( \<magnet>/media/Music/Фашисты/Black Heaven/Black Heaven - Discography (2001-2011), AAC/2011 - Dystopia/07 Himmel ohne Sterne.m4a</magnet> ) [Powered by DeaDBeeF 0.5.1 | GNU/Linux]

пример вывода в чат eiskaltdcpp:
/me DeaDBeeF playing now:Black Heaven - Himmel ohne Sterne, длина песни 3:59, уже прослушал 2:54 ( 07 Himmel ohne Sterne.m4a (9.1 МиБ) ) [Powered by DeaDBeeF 0.5.1 | GNU/Linux]]
3) Код
db=$(deadbeef --nowplaying "%a - %t, длина песни %l, уже прослушал %e")
directory=$(deadbeef --nowplaying "%D")
version=$(deadbeef --nowplaying "%V")
file=$(deadbeef --nowplaying "%f")
echo /me DeaDBeeF playing now:$db "( \<magnet>$directory/$file</magnet> )" "[Powered by DeaDBeeF $version | GNU/Linux]"
exit

//может пригодится кому)

**Attachment:** [db.sh](http://code.google.com/p/eiskaltdc/issues/detail?id=344#hc69)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on February 10, 2012 12:11:45_

Добавлен. Спасибо.

**Comment by dhamp** [comment]
_From [Vinni....@gmail.com](https://code.google.com/u/110849380905804537206/) on September 30, 2012 12:34:35_

А кто нибудь знает как сделать, что-бы аудиоплееры типа Amarok или Clementine сами уведомляли eiskaltdc++ о смене трека, и что-бы это приводило к выполнению команды выводящей текущий трек в чат ?! Так можно ? А то как-то сидеть и кнопку нажимать - это конечно лучше чем ничего, но, имхо, немного не логично ...

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
