### ISSUE TITLE
боковая панель и меню, даблклик в лс

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#128]
_From [nbs...@gmail.com](https://code.google.com/u/108083353536033146626/) on May 21, 2010 13:15:06_

хотелось бы, чтобы по правому клику мышкой в боковой панели на 
пользователях, с которыми открыта личка, открывалось то же контекстное 
меню, которое открывается при ПКМ на никах этих же пользователей в 
общем чате или списке пользователей. в данный момент там присутствует 
только один пункт: Close.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=508_

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on May 21, 2010 16:34:33_

А еще лучше то меню, которое открывается по кпм в списке пользователей.
Да еще и чтоб оно было при клике на пользователе в чате.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on May 22, 2010 01:13:14_

nbspjr, а теперь давай по пунктам, что там может быть кроме Close и 'Показать виджет'?

**Comment by dhamp** [comment]
_From [nbs...@gmail.com](https://code.google.com/u/108083353536033146626/) on May 22, 2010 07:25:23_

- добавить/удалить в/из избранные(ых)
- просмотр файлов
- согласовать очередь
- копировать данные
- пользовательское меню (если есть)
- меню хаба (если есть)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on January 23, 2011 11:25:42_

**Owner:** dein.negativ  
  **Labels:** -Priority-Medium Priority-Low

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
