### ISSUE TITLE
Отображаемые цвета

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#133]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 17, 2010 05:57:50_

Хотелось бы самому определять в настройках, как цвет так и фон файлов пользователя, которые уже есть у меня.
А так непонятно откуда он вообще берётся.

**Attachment:** [share.png](http://code.google.com/p/eiskaltdc/issues/detail?id=705)

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=705_

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 17, 2010 08:16:03_

r1744 - возможность изменять цвет шрифта уже расшаренных файлов.

**Status:** Accepted

**Comment by dhamp** [comment]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 20, 2010 18:45:38_

Появилась, но всё же работает не так как хотелось бы...

1 Настройки цвета для уже расшаренных файлов работают только при просмотре списков файлов пользователей, а при поиске они по прежнему неразличимы.

2 Даже при просмотре списка файлов, отображаются другим цветом лишь файлы, а папки как с частично расшаренными файлами, таки с полностью расшаренными файлами отображаются как будто они у меня из нет. r1772

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 21, 2010 07:19:49_

У меня все работает в поисковике

**Attachment:** [24.png](http://code.google.com/p/eiskaltdc/issues/detail?id=705#hc4)

**Comment by dhamp** [comment]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 21, 2010 15:41:40_

Мммм... вот в чём дело... Я использую быстрый поиск, вводя слово в панель быстрого поиска, откуда по умолчанию подсвечивать НЕ стоит и НЕ имеется возможности как то это переключить.
Раз такое дело, то сделайте поведение "Подсвечивать" по умолчанию, а то приходиться и в обычном поиске каждый раз выбирать подсветку и в быстром поиске вообще без подсветки.

**Attachment:** [s2.png](http://code.google.com/p/eiskaltdc/issues/detail?id=705#hc5)

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on September 21, 2010 15:57:34_

\> Раз такое дело, то сделайте поведение "Подсвечивать" по умолчанию

По-умолчанию будет "Ничего не делать"

\> приходиться и в обычном поиске каждый раз выбирать подсветку и в быстром поиске вообще без подсветки.

Опция запоминается только после того как с ней будет выполнен хоть один поисковой запрос (откройте окно поисковика, выберите "Подсвечивать" и начните поиск - теперь все вновь открываемые окна поиска будут подсвечиваться)

**Comment by dhamp** [comment]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 21, 2010 23:12:09_

Объясните мне пожалуйста, зачем пользователям вообще нужен режим с отсутствующей подсветкой уже имеющихся файлов, да ещё выбранный по умолчанию, помимо того, чтобы он подумал, что тут такой подсветки и вовсе нет ?

**Comment by dhamp** [comment]
_From [13I...@gmail.com](https://code.google.com/u/104216003544953986668/) on September 26, 2010 00:22:53_

Повторяюсь ёщё раз...

1. Хотелось бы что бы что бы отображались не только уже расшаренные файлы, но и полностью расшаренные папки тем же цветом, что и расшаренные файлы.
2. Хотелось бы что бы частично расшаренные папки так же помечались при поиске своим цветом отдельным цветом, который можно было бы установить.
3. Хотелось бы что бы действие выделять цветом было или по умолчанию, или, раз вам уж так хочется, состояние "ничего не делать" было приравнено к состоянию Подсвечивать.
Хотя там вполне бы хватило 2 состояния "Выделять" и "Скрывать".

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on December 03, 2010 11:47:05_

Issue 858 has been merged into this issue.

**Comment by dhamp** [comment]
_From [yuri-xa...@yandex.ru](https://code.google.com/u/112318394159763967949/) on November 14, 2011 10:08:09_

Добавлю свои 5 копеек в тему.
Ubuntu 10.04, последняя unstable-QT-версия (2.2.5 (100484c)).
На всплывающих подсказках (при наведении на значок программы в трее, при наведении на список отдаваемого в данный момент, наведение на строку статуса) белый текст на светлом фоне, ничего не читается. Перекопал опции, касающиеся цветов, но нигде не увидел белого цвета шрифта. Скрин такой подсказки прилагаю.

**Attachment:** [Снимок.png](http://code.google.com/p/eiskaltdc/issues/detail?id=705#hc10)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 14, 2011 10:19:27_

yuri-xarit, настройте используемую тему Qt. Для начала можно просто разные темы применить и посмотреть.

**Comment by dhamp** [comment]
_From [yuri-xa...@yandex.ru](https://code.google.com/u/112318394159763967949/) on November 14, 2011 22:01:45_

Поставил системную, почти хорошо. А вообще настройки цветов, которых нет в меню настроек, где-то меняются (в файлах конфигурации например) или только правкой исходных кодов делается?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on November 14, 2011 23:35:04_

1) Цветовая схема настраиваются в теме оформления.
2) Тема оформления общая для всех программ на Qt (для Gtk аналогично).
3) Все программы выглядят однотипно.

На стриншоте гном или юнити?

Не уверен, что системная тема оформления определяется корректно. Возможно имеет смысл выбрать тему Gtk+ и сравнить.

В любом случае, все это оффтопик. Потому что issue посвящен настройке цветов нестандартных элементов интерфейса (которых нет и не может быть в системной теме оформления).

**Comment by dhamp** [comment]
_From [yuri-xa...@yandex.ru](https://code.google.com/u/112318394159763967949/) on November 15, 2011 01:52:19_

Цвета фона на подсказках действительно из системной темы берутся -- был гном с дефолтной тёмной убунтовской темой, поменял на более светлую и фоны подсказок поменялись. Но цвет и размер шрифта остались теми же, что и были. Поэтому могу предположить, что они не связаны с общесистемной темой и выставляются самой программой.
Если считаете оффтопом -- потрите...

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
