### ISSUE TITLE
Не работает антиспам в комнатах

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#134]
_From [grey...@gmail.com](https://code.google.com/u/100032111855475059008/) on September 19, 2010 15:13:22_

Не работает антиспам с комнатами. 
т.е. если в черный список добавляю имя комнаты, она не блокируется.
Вроде как это из за того, что антиспам не проверяет черный список если приват уже открыт.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=710_

**Comment by dhamp** [comment]
_From [grey...@gmail.com](https://code.google.com/u/100032111855475059008/) on September 19, 2010 04:16:06_

антиспам в режиме фильтра*

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on February 19, 2012 04:05:24_

[patch]
diff --git a/eiskaltdcpp-qt/src/HubFrame.cpp b/eiskaltdcpp-qt/src/HubFrame.cpp
index dbe7803..01efef3 100644
--- a/eiskaltdcpp-qt/src/HubFrame.cpp
+++ b/eiskaltdcpp-qt/src/HubFrame.cpp
@@ -1847,7 +1847,7 @@ bool HubFrame::parseForCmd(QString line, QWidget *wg){
 QString HubFrame::getHubUrl() {
     if (client)
         return _q(client->getHubUrl());
\-    
+
     return "";
 }
 
@@ -3683,7 +3683,7 @@ void HubFrame::on(ClientListener::Message, Client*, const ChatMessage &message)
         third = message.thirdPerson;
 
     map["HUBURL"] = _q(client->getHubUrl());
\-    
+
     if(message.to && message.replyTo)
     {
         //private message
@@ -3699,7 +3699,7 @@ void HubFrame::on(ClientListener::Message, Client*, const ChatMessage &message)
         else if (isBot && BOOLSETTING(IGNORE_BOT_PMS))
             return;
 
-        CID id           = user->getUser()->getCID();
+        CID id           = message.from->getUser()->getCID();
         QString nick     =  _q(message.from->getIdentity().getNick());
         bool isInSandBox = false;
         bool isEcho      = (message.from->getUser() == ClientManager::getInstance()->getMe());
@@ -3754,7 +3754,7 @@ void HubFrame::on(ClientListener::Message, Client*, const ChatMessage &message)
             emit corePrivateMsg(map);
 
         if (!(isBot || isHub) && (message.from->getUser() != ClientManager::getInstance()->getMe()) && Util::getAway() && !hasPMWindow)
-            ClientManager::getInstance()->privateMessage(HintedUser(user->getUser(), client->getHubUrl()), Util::getAwayMessage(), false);
+            ClientManager::getInstance()->privateMessage(HintedUser(message.from->getUser(), client->getHubUrl()), Util::getAwayMessage(), false);
 
         if (BOOLSETTING(LOG_PRIVATE_CHAT)){
             string info = Util::formatAdditionalInfo(map["I4"].toString().toStdString(),BOOLSETTING(USE_IP),BOOLSETTING(GET_USER_COUNTRY));
[/patch]

у меня возможности проверить после этого патча работоспособность антиспама {в комнатах | вообще} нет.

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
