### ISSUE TITLE
EiskaltDC++ Gtk --- добавление настроек

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#151]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on February 23, 2011 13:58:55_

добавить настройки для следующего:
1) "sound-command"
2) SETTING(HASH_BUFFER_SIZE_MB), SETTING(HASH_BUFFER_POPULATE), SETTING(HASH_BUFFER_NORESERVE), SETTING(HASH_BUFFER_PRIVATE)
3) SETTING(AUTO_DETECT_CONNECTION)
4) SETTING(FAST_HASH) - лучше перенести из Расширенные->Расширенные и сгруппировать с настройками из пункта 2, кроме размера буфера он общий для обоих методов хэширования.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=995_

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 20, 2011 07:38:09_

SETTING(BIND_IFACE) - Integer
SETTING(BIND_IFACE_NAME) - String

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on April 01, 2011 12:03:29_

SETTING(SEGMENT_SIZE)

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on April 01, 2011 12:04:01_

SETTING(IP_TOS_VALUE)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 09, 2011 09:26:31_

SETTING(HASHING_START_DELAY)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 11, 2011 14:14:50_

https://github.com/negativ/eiskaltdcpp/commit/5c07d0c Добавил опцию "sound-command".
Начало положено!

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on May 06, 2011 02:33:12_

в диалог свойств избранного хаба добавить:
1)Mode
2)ClientId, OverrideId
3)ExternalIp

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on May 20, 2011 13:21:55_

IpFilter (IPFILTER) и  тултип к нему про перезапуск и файл ~/.config/eiskaltdc++/ipfilter

**Summary:** EiskaltDC++ Gtk --- добавление настроек

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on June 07, 2011 11:58:19_

setting(DYNDNS_SERVER)
setting(DYNDNS_ENABLE)

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 20, 2011 10:58:23_

"Mode" в избранных хабах теперь есть.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on June 20, 2011 22:11:30_

MINIMUM_SEARCH_INTERVAL в избранных хабах теперь есть.

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on July 18, 2011 21:18:07_

DHT, DHT_PORT, DYNDNS_ENABLE и DYNDNS_SERVER в диалоге настроек теперь есть.

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on March 30, 2012 07:24:36_

добавил отсутсвующие настройки в диалог свойств избранного хаба,
добавил пропущенные настройки на вкладку настроек логов. 
всё это пока в моей локально ветке

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on March 30, 2012 07:28:17_

Многовато изменений для ближайщего релиза. Могут быть непредвиденные регрессии. Может в отдельную ветку пушнешь?

**Comment by dhamp** [comment]
_From [egikpetrov](https://code.google.com/u/egikpetrov/) on March 30, 2012 07:45:47_

* [new branch]      gtk_settings -> gtk_settings

**Comment by tehnick** [comment]
Closing of outdated issue which is not useful in a current development of project.
