### ISSUE TITLE
EiskaltDC++ Qt --- Segmentation fault

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#210]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on March 10, 2012 17:16:15_

eiskaltdcpp-unstable-2.2.7-20120306-195821-b686cc1

Упала во время работы.

**Attachment:** [bug18.txt](http://code.google.com/p/eiskaltdc/issues/detail?id=1300)

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1300_

**Comment by pavelvat** [comment]
Obsolete.
