### ISSUE TITLE
EiskaltDC++ Qt --- Segmentation fault

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#212]
_From [pavelvat@gmail.com](https://code.google.com/u/pavelvat@gmail.com/) on March 18, 2012 00:12:05_

2.2.7 (4daa56a)
Ubuntu 11.10

программа упала во время добавления файла на закачку из результатов поиска.

**Attachment:** [bug19.txt](http://code.google.com/p/eiskaltdc/issues/detail?id=1305)

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1305_

**Comment by pavelvat** [comment]
Obsolete.
