### ISSUE TITLE
Gtk UI: dialog window for configuring antispam filter

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#217]
_From [aadybal@gmail.com](https://code.google.com/u/aadybal@gmail.com/) on March 22, 2012 17:18:42_

Прикрутите уже наконец пароль на личку. На популярных инет-хабах с 10000 юзеров невозможно находится. За пять минут нахождения на хабе, открывается двадцать окон со спамом, а если отойдешь, то когда вернешься, клиент сожрёт всю оперативу и повиснет намертво вместе с иксами.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1310_

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on March 22, 2012 10:19:53_

Настройте уже наконец антиспам. Он присутствует в программе, начиная с самых первых версий.

**Status:** NotConfirmed

**Comment by dhamp** [comment]
_From [aadybal@gmail.com](https://code.google.com/u/aadybal@gmail.com/) on March 23, 2012 07:41:28_

Окай. И где его настроить? Если бы он присутствовал в очевидной форме, я бы его уже давно настроил.

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on March 24, 2012 11:22:20_

АнтиСпам существует только для Qt версии приложения. В главном меню: Инструменты -> Модуль антиспама. Для GTK версии этот функционал недоступен.

**Comment by dhamp** [comment]
_From [aadybal@gmail.com](https://code.google.com/u/aadybal@gmail.com/) on May 27, 2013 16:00:48_

А когда на GTK версию прикрутите антиспам фильтр?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on May 31, 2013 14:44:59_

**Summary:** Gtk UI: dialog window for configuring antispam filter  \<span class="oldvalue"> (was: Пароль на личку.) \</span>  
  **Status:** New  
  **Labels:** -Type-Defect -Priority-Medium Type-FeatureRequest Priority-Low

**Comment by tehnick** [comment]
GTK+ UI will be removed soon.
