### ISSUE TITLE
uploads doesn't start

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#219]
_From [hg2rbw](https://code.google.com/u/hg2rbw/) on April 20, 2012 14:58:29_

What version of the product are you using? EiskaltDC++ 2.2.7 05e64ee Qt On what operating system? Arch Linux x86_64 What steps will reproduce the problem? 1.Boot up your operation system
2.Run EiskaltDC++
3.You will see the progress bars won't move.
4.When i quit from the program and restart it the uploads are running immediately. What is the expected output? What do you see instead? Please provide any additional information below: I don't know anything else, but if you help me how should i get more debug information, i'll enclose it.
(I didn't use to download but i guess it's the same with download)
1. Qt version 4.8.1
2. libc version 2.15

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1321_

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 20, 2012 06:29:11_

\> You will see the progress bars won't move.

Are the downloads paused in this case?

Which type of network connection are you using?

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 20, 2012 06:30:46_

Hmm, uploads but not downloads. So the first question is unnecessary.

**Comment by dhamp** [comment]
_From [hg2rbw](https://code.google.com/u/hg2rbw/) on April 20, 2012 07:00:59_

tehinck: nope, i used to shutdown my eiskalt with my computer. In the past kde start it automatically with other program which i ran before shutdown my computer. But eiskalt won't start (i think it's another issue).

**Comment by dhamp** [comment]
_From [hg2rbw](https://code.google.com/u/hg2rbw/) on April 20, 2012 07:11:18_

ohh Sorry... i use my DC with Manual Port forward

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on April 20, 2012 07:15:07_

1) Have you seen any warnings in system log?
2) Can you reproduce this problem, when client is configured to passive mode?

**Comment by dhamp** [comment]
_From [hg2rbw](https://code.google.com/u/hg2rbw/) on April 20, 2012 07:24:09_

1. Nope
2. Yes i can.

**Comment by dhamp** [comment]
_From [hg2rbw](https://code.google.com/u/hg2rbw/) on April 20, 2012 07:25:20_

It write the speed, but the progress bar is stopped, and time left too

**Comment by ValdikSS** [comment]
@tehnick https://bugs.launchpad.net/dcplusplus/+bug/1656050
