### ISSUE TITLE
GTK - Add in Tools a tab for viewing System.log.

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#233]
_From [markus.l...@gmail.com](https://code.google.com/u/102176934983476662849/) on November 02, 2012 13:28:23_

Add a tab for viewing messages in System.log.

Possible Highlight errors or filter for ignoring file hashing.

Maybe open it automatically in error situations/new events (like SSH problems, file permissions problems etc.) or possibilty to select Auto-open in setting Appearance Windows.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1371_

**Comment by tehnick** [comment]
GTK+ UI will be removed soon.
