### ISSUE TITLE
cmake fails on "idna (headers)"

### ISSUE THREAD

**Issue by ivasim** [eiskaltdcpp/eiskaltdcpp#291]
Hi, I tried to compile latest eiskaltdcpp sources and this is the error I'm getting:

    (...)
    -- CMAKE will use this libs (and headers) during build:
     
        miniupnpc (headers): ()
        lua (headers):  ()
        boost (headers):  (/usr/include)
        bzip2 (headers): /usr/lib/x86_64-linux-gnu/libbz2.so (/usr/include)
        zlib (headers): /usr/lib/x86_64-linux-gnu/libz.so (/usr/include)
        openssl (headers): /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (/usr/include)
        iconv (headers): /usr/lib/x86_64-linux-gnu/libc.so (/usr/include)
        aspell (headers):  ()
        gettext (headers):  (/usr/include)
        pcre(cpp) (headers):  ()
        idna (headers):  (IDNA_INCLUDE_DIR-NOTFOUND)
       
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    IDNA_INCLUDE_DIR
       used as include directory in directory /home/user/eiskaltdcpp/dcpp
     
    -- Configuring incomplete, errors occurred!

System is Debian Wheezy 7.8.0 64bit.
This is the command that I used on cmake:
"cmake -DUSE_IDNA=OFF -DWITH_DEV_FILES=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ../"
I thought that using "-DUSE_IDNA=OFF" will solve the problem but it didn't, also I'm not sure if "-DWITH_DEV_FILES=OFF" could cause any future problems but I used it anyway?
The most interesting thing is that I successfully compiled latest source with the same command stated above on my RaspberryPi/Raspbian system. I might be missing some packages but both systems have identical packages installed according to requirements for compiling and installing eiskaltdcpp.
I also searched for "*idna*" expression and both systems have 
./usr/include/unicode/idna.h
./usr/include/unicode/uidna.h
if that has anything to do with the error.

Thank you!

**Comment by ivasim** [comment]
I solved the problem but not really sure what caused it. I just edited the line in CMakeLists.txt 
"option (USE_IDNA "Use libidn for punycode generation" ON")  by changing the option to OFF, 
created new "bulddir", ran cmake again and it worked.

**Comment by dhamp** [comment]
USE_IDNA - try find and use package libidn (http://www.gnu.org/software/libidn/)
/usr/include/unicode/idna.h - this file contains in icu(http://www.icu-project.org/) package on my system.

described in the original message was probably because it was in your system was installed package with a library libidn, but has not been established packet headers for her.
for debian is likely libidn-dev.

**Comment by gautamsreekumar** [comment]
I tried installing libidna-punycode-perl, IDNA package using pip, and libidn11-dev in Ubuntu 16.04. It worked when I installed libidn11-dev, but not sure if the other two packages were required or not.

**Comment by vovochka404** [comment]
No, they aren't. Only libidn11-dev is needed.
