### ISSUE TITLE
TLS v1.2

### ISSUE THREAD

**Issue by synaomen** [eiskaltdcpp/eiskaltdcpp#293]
Is Eiskalt TLS v1.2 compatible? Some Luadch hubs like to change to this version.

**Comment by synaomen** [comment]
I make a test with Luadch with enabled tls v1.2
http://sourceforge.net/projects/luadch/files/Luadch/v2.00/Luadch_v2.00_svn412_debian.7z/download
change the cfg/cfg.tbl from 
protocol = "tlsv1",  -- do not touch this 
to
protocol = "tlsv1_2",  -- do not touch this

Now when i try to connect the testhub:
18:10:24] *  Verbinde mit adcs://127.0.0.1:5001
[18:10:24] *  Fehlgeschlagen: SSL-Fehler: error:00000001:lib(0):func(0):reason(1) (0, 1)...

No connection can be established. Eiskaltdc is not compatible with TLS v1.2. With Jucy v0.87 i can connect and its the only one linux client for this at the moment. The new dc++ v8.5 has TLS v1.2 support, but they castrate this on AES128. the AES256 code is deaktivatet. I've a interesting conversation about this with the AirDC Developer.

Can you solve the problem please!!!

**Comment by pavelvat** [comment]
#309
