### ISSUE TITLE
Enable upnp for DHT port

### ISSUE THREAD

**Issue by vovochka404** [eiskaltdcpp/eiskaltdcpp#296]
Если используется upnp и dht - следует так же прокидывать dht порт по средствам upnp

**Comment by pavelvat** [comment]
Он и так прокидывается, просто сообщение в строке уведомлений выводится без учёта DHT.

**Comment by vovochka404** [comment]
Да, есть такое.
Просто он не прокидывается если его включить уже после подключения.
Нужно переподключаться.
