### ISSUE TITLE
Fill users IP by search results

### ISSUE THREAD

**Issue by vovochka404** [eiskaltdcpp/eiskaltdcpp#297]
Может стоит заполнять пользовательские IP по результатам поиска?
Было бы удобненько :)

**Comment by vovochka404** [comment]
Возможно оно заполняется, но не показывается/обновляется в списке пользователей?

**Comment by buggyman** [comment]
IP показывается если вы в активном режиме. Наверное у вас пассивный режим и хаб скрывает эту информацию, - тогда клиенту взять его неоткуда.

**Comment by vovochka404** [comment]
Хаб может скрывать эту информацию независимо от режима.

Тем не менее, в ответе на поисковый запрос содержиться как nick так и ip.
Так же поисковый запросы пользователей (активных) могут содержать ip.

Сейчас не могу проверить, но у меня сложилось впечатление что ip из поисковых результатов уже используются, но не показываюстя в списке пользователей. Пока не могу проверить, позже сегодня отпишусь.

**Comment by vovochka404** [comment]
Да.
Так и есть.

Хаб, IP не видно.

Если скачать с человека из чата список файлов или он пришлет результат поиска, то в чате у этого человека начинает светится IP, но в списке пользователей этот IP не показывается.

Считаю надо исправить сей досадный момент :)

**Comment by buggyman** [comment]
А, так вы про IP в чате и списке пользователей? Пардон, не так понял вопрос.

**Comment by vovochka404** [comment]
В списке пользователей конечно :)

Ну а вообще: везде :)

**Comment by buggyman** [comment]
Тогда присоединяюсь к запросу. Также видел такое поведение на некоторых хабах: если что-то сказать в чате хаба, скрывающего IP юзеров, то к тебе коннектятся некоторые пользователи, но сразу отключаются, ничего не скачав. Думаю, что это для выяснения IP, т.к. дальнейшее общение в чате (до перезахода на хаб) не вызывает подобной реакции.

**Comment by vovochka404** [comment]
Да, такое поведение есть у грейлинка, и оно меня раздражает.

Не считаю что ейскальту нужно такое активное выяснение IP адресов, но тем не менее, если IP пользователя уже засветился каким-либо образом, не плохо было бы доавить эту информацуию в пользователя в списке пользователей.
