### ISSUE TITLE
Upload download ration resets in OS X

### ISSUE THREAD

**Issue by FlugelderFreiheit** [eiskaltdcpp/eiskaltdcpp#300]
version 2.3.0 OS X
When the application is quit the upload and download stats do not get stored. When the application is started the next time total downloads becomes equal to total uploads size and the ratio gets reset to 1.000. Please suggest the reason and possible solution for this.

**Comment by tehnick** [comment]
You are using the testing version of program now, because where are no app bundle for last stable release (v2.2.10) yet. You may wait until it will be build and uploaded into Download section of our project at SourceForge or you may build program from sources.

**Comment by tehnick** [comment]
Unfortunately sourceforge.net is still partially broken and we cannot upload files there.
Please try these two application bundles:
https://drive.google.com/open?id=0B8NP67LYQJcnNHRBVUJTeW5Lek0
https://drive.google.com/open?id=0B8NP67LYQJcnbml5cV9pa0ZPYjQ

**Comment by tehnick** [comment]
Hi,

Please try the last build (`2.2.10-228-macOS10.11`) of EiskaltDC++ from here:
https://sourceforge.net/projects/eiskaltdcpp/files/macOS/devel/
Or you [may install it](https://github.com/Homebrew/homebrew-cask/pull/51111) using homebrew.

Despite this version looks less than previous, it is more recent. Yes, we have used very strange versioning scheme for development builds in the past... See short discussion with homebrew maintainer: https://github.com/Homebrew/homebrew-cask/pull/51111
