### ISSUE TITLE
crash: 2.2.10 - crashed on reconnect

### ISSUE THREAD

**Issue by vovochka404** [eiskaltdcpp/eiskaltdcpp#301]
---

EiskaltDC++ version: 2.2.10 stable
Oops! Please report a bug at http://code.google.com/p/eiskaltdc/issues/list

Stacktrace below is usually useless. Useful bug report should include full backtrace:
https://code.google.com/p/eiskaltdc/wiki/issue_hints_en

Stacktrace:
stack trace:
  /lib64/libc.so.6 : ()+0x35200  [0x7f0090f41200]
  /usr/lib64/libQtGui.so.4 : QSortFilterProxyModel::parent(QModelIndex const&) const+0x56  [0x7f0092e86076]
  /usr/lib64/libQtCore.so.4 : QAbstractItemModelPrivate::rowsAboutToBeInserted(QModelIndex const&, int, int)+0xde  [0x7f0091f031de]
  /usr/lib64/libQtCore.so.4 : QAbstractItemModel::beginInsertRows(QModelIndex const&, int, int)+0x75  [0x7f0091f04b85]
  /usr/lib64/libQtGui.so.4 : ()+0x74f21a  [0x7f0092e8821a]
  /usr/lib64/libQtGui.so.4 : ()+0x7526ba  [0x7f0092e8b6ba]
  /usr/lib64/libQtGui.so.4 : ()+0x7528ef  [0x7f0092e8b8ef]
  /usr/lib64/libQtCore.so.4 : QMetaObject::activate(QObject_, QMetaObject const_, int, void*_)+0x2da  [0x7f0091f221fa]
  /usr/lib64/libQtCore.so.4 : QAbstractItemModel::rowsInserted(QModelIndex const&, int, int)+0x44  [0x7f0091f6c4c4]
  /usr/lib64/libQtCore.so.4 : QAbstractItemModel::endInsertRows()+0xde  [0x7f0091f0723e]
  /usr/bin/eiskaltdcpp-qt : UserListModel::addUser(boost::intrusive_ptrdcpp::User const&, dcpp::Identity const&, QString const&, bool)+0x290  [0x559540]
  /usr/bin/eiskaltdcpp-qt : HubFrame::userUpdated(boost::intrusive_ptrdcpp::User const&, dcpp::Identity const&)+0x357  [0x5a4207]
  /usr/bin/eiskaltdcpp-qt() [0x549278]
  /usr/lib64/libQtCore.so.4 : QObject::event(QEvent_)+0x24e  [0x7f0091f2659e]
  /usr/lib64/libQtGui.so.4 : QWidget::event(QEvent_)+0xb1b  [0x7f0092965c5b]
  /usr/lib64/libQtGui.so.4 : QApplicationPrivate::notify_helper(QObject_, QEvent_)+0x8c  [0x7f009291676c]
  /usr/lib64/libQtGui.so.4 : QApplication::notify(QObject_, QEvent_)+0x22d  [0x7f009291ccad]
  /usr/lib64/libQtCore.so.4 : QCoreApplication::notifyInternal(QObject_, QEvent_)+0x6d  [0x7f0091f0e2ad]
  /usr/lib64/libQtCore.so.4 : QCoreApplicationPrivate::sendPostedEvents(QObject_, int, QThreadData*)+0x1ed  [0x7f0091f1157d]
  /usr/lib64/libQtCore.so.4 : ()+0x1b08fe  [0x7f0091f3b8fe]
  /usr/lib64/libglib-2.0.so.0 : g_main_context_dispatch()+0x254  [0x7f008f869a04]
  /usr/lib64/libglib-2.0.so.0 : ()+0x4bc48  [0x7f008f869c48]
  /usr/lib64/libglib-2.0.so.0 : g_main_context_iteration()+0x2c  [0x7f008f869cec]
  /usr/lib64/libQtCore.so.4 : QEventDispatcherGlib::processEvents(QFlagsQEventLoop::ProcessEventsFlag)+0x7e  [0x7f0091f3b0be]
  /usr/lib64/libQtGui.so.4 : ()+0x27a676  [0x7f00929b3676]
  /usr/lib64/libQtCore.so.4 : QEventLoop::processEvents(QFlagsQEventLoop::ProcessEventsFlag)+0x2f  [0x7f0091f0ce6f]
  /usr/lib64/libQtCore.so.4 : QEventLoop::exec(QFlagsQEventLoop::ProcessEventsFlag)+0x175  [0x7f0091f0d165]
  /usr/lib64/libQtCore.so.4 : QCoreApplication::exec()+0x89  [0x7f0091f125b9]
  /usr/bin/eiskaltdcpp-qt : main()+0x5ff  [0x49f62f]
  /lib64/libc.so.6 : __libc_start_main()+0xf5  [0x7f0090f2db05]
  /usr/bin/eiskaltdcpp-qt() [0x532d2e]
Installing handler for: Ошибка сегментирования
Installing handler for: Аварийный останов
Installing handler for: Ошибка шины
Installing handler for: Завершено

**Comment by pavelvat** [comment]
https://github.com/eiskaltdcpp/eiskaltdcpp/wiki/How-to-make-bugreport
