### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by whoizit** [eiskaltdcpp/eiskaltdcpp#308]
Дак чо там с ipv6? Не соединяется

**Comment by vovochka404** [comment]
А какой хаб нынче поддерживает IPv6?
Птоха?


Просто под рукой лишь старый верлик...

**Comment by atommixz** [comment]
PtokaX 0.5 и выше, выпущенный ещё в 2012 году

**Comment by atommixz** [comment]
Все ADC хабы поддерживают ipv6 https://ru.wikipedia.org/wiki/Advanced_Direct_Connect

**Comment by atommixz** [comment]
http://sourceforge.net/projects/adchpp/

**Comment by buggyman** [comment]
IPv6 в ближайшей версии точно не будет, т.к. она использует ещё старое ядро. Новое ядро в гите в ветке 'dcppsyncv4' - вот там есть поддержка IPv6, при желании можно потестировать.

**Comment by buggyman** [comment]
Есть новая инсайдерская инфа - IPv6 не будет в эйскальте никогда, т.к. старое ядро работает стабильно (а оно не поддерживает в6)... Менять это ядро или вносить поддержку для IPv6 в текущее никто из разработчиков не хочет :(

**Comment by atommixz** [comment]
да вообще пофиг, поднял в cjdns uhub и мы коннектимся туда через ncdc. можете закрывать если хотите.

**Comment by whoizit** [comment]
дубликат https://github.com/eiskaltdcpp/eiskaltdcpp/issues/165
