### ISSUE TITLE
TLS 1.2 / 1.0

### ISSUE THREAD

**Issue by gkreidl** [eiskaltdcpp/eiskaltdcpp#320]
@tehnick:
Your changes in cryptomanager were based on my code suggestions on gist. I don't mind if you modify them, but why did you remove the TLS 1.0 ciphers completely? I think they are still important as fallback when connecting to older clients:
DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:AES128-SHA

**Comment by gkreidl** [comment]
I can now confirm that the new cryptomanager cannot connect to older adcs hubs. I installed a new build from ppa:alex-p/notesalexp-precise eiskaltdcpp-unstable  2.2.9+git20150727-1ppa1~precise1 and it could only connect to hubs that already support TLS-1.2 ( I suppose that also is true for clients that don't support TLS 1.2 but didn't test it).
The versions I built myself for Ubuntu 14.04 and for the Raspberry PI could connect to all hubs/clients. I used https://gist.github.com/gkreidl/876c6277995184f250a4 with the following:
const char ciphersuites[] = "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:AES128-SHA";

**Comment by gkreidl** [comment]
Any chance to get this fixed in the near future?

**Comment by tehnick** [comment]
a9c136c8707280d0eeb66be6b289d9718287c55c

**Comment by gudjev** [comment]
Hello,
sorry for the lame question.
But i can not find such file into the folder or elsewhere. How could i fix that problem?
Copy the source code and to create a file called CryptoManager.cpp ?
And if so where should i put that file?

Again sorry, but I'm total noob with Linux
