### ISSUE TITLE
Support for OS 10.11?

### ISSUE THREAD

**Issue by happycadaver** [eiskaltdcpp/eiskaltdcpp#321]
Up to Developer Preview 5 Eiskalt has been working fine, but since DP6 i'm not able to search or down/upload anything from/to my hubs.

Does anyone use the client under 10.11 or will there be a release of Eiskalt when El Capitan is officially released?

**Comment by happycadaver** [comment]
There seem to be 2 newer versions for Mac, ending with "qt4/qt5". Both versions won't start up with El Capitan DP6. I'm using the the 2.30 version from 2013, but with this i have the a.m. issues.

**Comment by happycadaver** [comment]
Older versions of Eiskalt don't work with El Capitan Beta as well. So if you want to use Eiskalt in the future you shouldn't update to El Capitan on release date as long there won't be an update of Eiskalt for Mac. With Yosemite there are no issues.

**Comment by happycadaver** [comment]
Will there be any feedback in a foreseeable future? Or do i have to look for a new client?

**Comment by tehnick** [comment]
We have only one maintainer with OS X now. And he uses OS X 10.9 for builds and tests of app bundles with EiskaltDC++. Also we have very few active OS X users who can check your problem. But no one of them uses OS X El Capitan. Currently I may suggest you only one thing: try to compile EiskaltDC++ from sources in your system environment (i.e. using compiller and system libraries shipped in this version of OS X).

**Comment by happycadaver** [comment]
No problem, thanks for the feedback.

I have never done any compiling, but maybe i will figure it out with some wiki searching. Or is this a lost cause without experience? I have an IT background, but mostly for hardware and networking equipment.

**Comment by tehnick** [comment]
I would recommend to search info about MacPorts, Fink and Homebrew. These package management systems are significantly simplify the manual build of programs from sources in OS X.

**Comment by happycadaver** [comment]
I have figured it out myself. Apparently port forwarding seems to be only working with a static IP and not with DHCP. I have no idea, why there is a difference, because every other software i own which needs port forwarding does work without issues.
