### ISSUE TITLE
SSL Error: error:00000001:lib(0):func(0):reason(1) (-1, 1)...

### ISSUE THREAD

**Issue by Sopor-** [eiskaltdcpp/eiskaltdcpp#324]
I tested your EiskaltDC++ 2.3.0 (v2.2.10-78-g8f1922b) and when i try to connect to Flexhub i get this error message: SSL Error: error:00000001:lib(0):func(0):reason(1) (-1, 1)...

I believe this has something to do with issue #320?

Almost every cipher is for TLSv1.2.
You seems to only have one cipher to use ECDHE-RSA-AES256-SHA, you need to have a lot more.

AirDC++:
			"ECDHE-ECDSA-AES128-GCM-SHA256:"
			"ECDHE-RSA-AES128-GCM-SHA256:"
			"ECDHE-ECDSA-AES128-SHA256:"
			"ECDHE-RSA-AES128-SHA256:"
			"ECDHE-RSA-AES128-SHA:"
			"DHE-RSA-AES128-SHA:"
			"AES128-SHA:"
			"ECDHE-ECDSA-AES256-GCM-SHA384:"
			"ECDHE-RSA-AES256-GCM-SHA384:"
			"ECDHE-ECDSA-AES256-SHA384:"
			"ECDHE-RSA-AES256-SHA384:"
			"ECDHE-ECDSA-AES256-SHA:"
			"ECDHE-RSA-AES256-SHA:"
			"AES256-GCM-SHA384:"
			"AES256-SHA256:"
			"AES256-SHA";

**Comment by gkreidl** [comment]
Yes, it's the same as issue #320.
In my source code proposal I used the same cipherlist as AirDC++, only in a slightly different order, and this is working with all older adcs hubs and clients.

**Comment by croutch** [comment]
I have this issue to. I sit in 4 hubs and two change the tls cipher to a new one,so i had to uninstall eiskalt and install the git package and could login again. But the two that works before with the old cipher stop working with this error SSL Error: error:00000001:lib(0):func(0):reason(1) (-1, 1).

**Comment by gkreidl** [comment]
Did you compile the gut package? If so, you could use my modified source instead which is working. I compiled versions for Ubuntu 14.04 and Raspbian and they work fine.

**Comment by croutch** [comment]
I installed the git package for arch linux from aur.
https://aur.archlinux.org/packages/eiskaltdcpp-core-git/
https://aur.archlinux.org/packages/eiskaltdcpp-daemon-git/
https://aur.archlinux.org/packages/eiskaltdcpp-data-git/
https://aur.archlinux.org/packages/eiskaltdcpp-qt-git/
I dont know how to replace the old file to yours in that way.

I gone try to do a full install from git instead.

**Comment by mikolola** [comment]
I get this when connecting: 
*  Fail: SSL Error: error:00000001:lib(0):func(0):reason(1) (0, 1)...
I kind of feel it is related. Running 2.2.9 on Linux Mint Debian ed.
Any suggestions? Thanks

**Comment by bulkware** [comment]
gkreidl: do you have a ppa or similar where I could obtain and test your deb-packages?

**Comment by tehnick** [comment]
a9c136c8707280d0eeb66be6b289d9718287c55c
