### ISSUE TITLE
Hub not working on 2.3.0 - Fail: SSL Error: error:00000001:lib(0):func(0):reason(1) (0, 1)...

### ISSUE THREAD

**Issue by oneseventhree** [eiskaltdcpp/eiskaltdcpp#328]
I try and connect to my server with 2.2.9 and works fine but when I try 2.3.0 it says:
Fail: SSL Error: error:00000001:lib(0):func(0):reason(1) (0, 1)...

Then in 2.9.0 it won't allow me to download anything even though the servers are up and active:
![screen shot 2015-10-09 at 2 20 33 pm](https://cloud.githubusercontent.com/assets/15043282/10385167/fe2a9402-6e90-11e5-89ab-653fda2d0081.png)
It just stays on this for days and days

 and it shows a GHOST picture on everything:
![screen shot 2015-10-09 at 2 19 57 pm](https://cloud.githubusercontent.com/assets/15043282/10385166/fe28017e-6e90-11e5-9b24-c40185ab89be.png)

**Comment by tehnick** [comment]
Unconfirmed. Please reopen if you still have this problem.
