### ISSUE TITLE
Segfault on Search

### ISSUE THREAD

**Issue by gnarula** [eiskaltdcpp/eiskaltdcpp#334]
Backtrace: https://gist.github.com/gnarula/8b7f85c9be3fa70910f0

Steps to reproduce: Search anything. Usually segfaults when the search is complete.

EiskaltDC++ version: 2.2.10-126-gb881208
GTK+ version: 3.18.7
Glib version: 2.46.2
OS: Archlinux
Kernel: 4.4.1

**Comment by tehnick** [comment]
GTK+ UI is unsupported now. Sorry.
