### ISSUE TITLE
Cannot create 2 favourites hubs with same address

### ISSUE THREAD

**Issue by SlackDeb** [eiskaltdcpp/eiskaltdcpp#341]
I have two different accounts on a hub. It seems Eiskalt has problems handling two favourites if the address is the same:
- when trying to make a second favourite with different credentials, when I hit OK it (IIRC) changed the details of the first favourite and didn't create the 2nd.
- I made the 2nd favourite with an address of "test", filled out login details and OK'd it. Then modified it and OK'd it. Double clicked and was told the username was taken on the hub, Eiskalt had acted like I clicked on the first favourite.
- making the 2nd favourite with the IP instead of a hostname and it behaves as expected

The hub's private, but the URI is something like:
adcs://host.domain.tld:port/?kp=SHA256/LONGSTRING

Is Eiskalt internally using the URI to index the favourites? If you are to use data from the user, surely the favourite's name would be better - I have given my two favourites different names. Though isn't it just best to index them uniquely somehow behind the scenes?

Thanks a lot.

**Comment by tehnick** [comment]
> Is Eiskalt internally using the URI to index the favourites?

Yes. But this is not a bug, but a feature for prevention of creating duplicates.
