### ISSUE TITLE
Close button hidden by scrollbar in sidebar

### ISSUE THREAD

**Issue by Kishore96in** [eiskaltdcpp/eiskaltdcpp#349]
I am using version 2.2.10 on Arch Linux [https://aur.archlinux.org/packages/eiskaltdcpp-qt/](url).
In the qt UI, the close button in the sidebar gets hidden by the scrollbar.
Image below shows the close buttons.
![close_button](https://cloud.githubusercontent.com/assets/23440033/20374106/3dc4d8f8-ac9c-11e6-98a2-cf751a986285.png)
Image below shows how the close buttons get hidden by the scrollbar in the sidebar.
![hidden_close_button](https://cloud.githubusercontent.com/assets/23440033/20374107/3dc7e8a4-ac9c-11e6-8d9c-a921d3fa36a3.png)

**Comment by tehnick** [comment]
Build with Qt5 does not have such issue. Update your PKGBUILD or use eiskaltdcpp-qt-git until 2.4.0 is released.

**Comment by Kishore96in** [comment]
@tehnick 
Sorry, but I am still having this issue after building eiskaltdcpp-qt-git. The 'Help > About Qt' dialog says the Qt version used is 5.9.1. 'Help > About EiskaltDC++' lists the Eiskalt version as 2.2.10-180-g4c9cbf20. Can you confirm which version the issue is fixed in?

**Comment by tehnick** [comment]
@Kishore96in I cannot reproduce your problem with QtCurve and Oxygen themes of Qt. Which themes have you tested?

**Comment by tehnick** [comment]
Test other themes. Most probably the root of problem is here.

**Comment by Kishore96in** [comment]
With the Breeze widget style, the buttons are completely hidden. With Oxygen, the buttons are almost completely visible, and then if I click on the close button, the current tab closes, the alignment of items changes, and the other buttons are now completely visible, and instead a portion of the left side is cut off (note how the arrows on the left to expand and collapse the list are partially hidden now). This doesn't seem to depend on how wide the sidebar is made.

Before clicking a close button with Oxygen widget style:
![Oxygen before clicking a close button](https://user-images.githubusercontent.com/23440033/31418380-5bbd2f86-ae53-11e7-9771-1f1390ed2b02.png)

After clicking a close button with Oxygen widget style:
![Oxygen after clicking the close button](https://user-images.githubusercontent.com/23440033/31418443-a775e396-ae53-11e7-8dd4-d44ce4fb2490.png)

Also note that the Breeze theme exhibits a padding issue even without the scrollbar.
Breeze without the scrollbar, before clicking a close button:
![screenshot_20171011_071732](https://user-images.githubusercontent.com/23440033/31418553-43dc05e4-ae54-11e7-9fe8-c85ab49e5d00.png)

Breeze without the scrollbar, after clicking a close button:
![screenshot_20171011_071914](https://user-images.githubusercontent.com/23440033/31418592-811c860e-ae54-11e7-8427-9e896dea85db.png)

Breeze with scrollbar, before clicking a close button:
![screenshot_20171011_072031](https://user-images.githubusercontent.com/23440033/31418616-ae1d7d52-ae54-11e7-92a8-20add61c94ac.png)

Note that in the above case, the scroll button is completely unclickable, since it is completely below the scrollbar, so I don't know if clicking it would expose a similar issue to the Oxygen theme.

**Comment by tehnick** [comment]
6324ff67771dfca5a09bf1a110fcf057871da99c
