### ISSUE TITLE
Error: Invalid params in JSON-RPC request.

### ISSUE THREAD

**Issue by 13werwolf13** [eiskaltdcpp/eiskaltdcpp#350]
when I try to find something that I get an error Error: Invalid params in JSON-RPC request.
![screenshot_20161226_154628](https://cloud.githubusercontent.com/assets/3271641/21479922/b5c5c2e0-cb82-11e6-9c31-c33efae2c99d.png)
everything else is working properly
P.S.: sorry for my english

**Comment by 13werwolf13** [comment]
Ну блин, неужели никто не поможет?! надоело убивать демона и поднимать гуй чтобы что-то скачать

**Comment by pavel-pimenov** [comment]
Запусти демона с -D
( --debug\t Debug mode)

Он тогда будет плевать в консоль все JSON-ы
сохрани это в файлик и покажи конец когда ругается.
по коду можно посмотреть какого атрибута не хватает
bool JsonRpcMethods::ListShare(const Json::Value& root, Json::Value& response)
{
    if (isDebug) std::cout << "ListShare (root): " << root << std::endl;

**Comment by tehnick** [comment]
Fixed in master branch: https://github.com/eiskaltdcpp/eiskaltdcpp-web
