### ISSUE TITLE
TLS in version EiskaltDC++ 2.3.0 (8c41579)

### ISSUE THREAD

**Issue by otrdiplomat** [eiskaltdcpp/eiskaltdcpp#351]
Used EiskaldDC a couple of years ago.  Downloaded and started using version 2.3.0 because of all the hubs going to TLS.  Can not get this version to connect to any hub that uses TLS.  Tried changing ports numerous times and no change.  Is there something that I could be doing wrong or does TLS not work in this version.  Is their an earlier version that it might work in that I could install.  I do not know anything about compiling so I am using the standard version.  Thanks

**Comment by tehnick** [comment]
Which operation system do you use?

**Comment by otrdiplomat** [comment]
Sorry for the delay in getting back to you.  I use MAC OS High Sierra Version 10.13.3.  Any help would be greatly appreciated.  Thanks

**Comment by otrdiplomat** [comment]
and my version is EiskaltDC++ 2.3.0 (8c41579)

**Comment by tehnick** [comment]
The current version of EiskaltDC++ from master branch has TLS 1.2 support. But you need build it yourself or find somebody who could build it for macOS.

**Comment by tehnick** [comment]
As for the nearest stable release (2.4.0): I do not know when it will happen, unfortunately.

**Comment by otrdiplomat** [comment]
Thank you very much for your reply.
