### ISSUE TITLE
Как увеличить количество слотов?

### ISSUE THREAD

**Issue by klug-pro** [eiskaltdcpp/eiskaltdcpp#353]
Как увеличить количество слотов и сделать его больше 100? Например 1000. Использую Ubuntu 12.04 и Ubuntu 14.04. Полагаю, что надо где-то в исходниках поменять и собрать под свою версию.
P.S.: Пробовал конфиг менять, так он сбрасывается при каждом запуске программы. В самой же программе ограничение в 100 слотов.

**Comment by pavel-pimenov** [comment]
Ищи в исходниках SLOTS

**Comment by klug-pro** [comment]
Так и не нашёл я где именно в исходниках выставляется ограничение. Где выставляется значение по умолчанию на количество слотов я вижу, но от перемены его максимальное значение всё-равно прежнее.

**Comment by tehnick** [comment]
> где именно в исходниках выставляется ограничение

В файлах `eiskaltdcpp-qt/ui/UISettingsSharing.ui` и `eiskaltdcpp-qt/ui/UISettingsConnection.ui` с помощью Qt Designer можно отредактировать свойства элементов `spinBox_UPLOAD` и `spinBox_ALTERNATE_SLOTS` соответственно.

**Comment by klug-pro** [comment]
А в GTK версии в каких файлах менять это ограничение?

**Comment by tehnick** [comment]
> А в GTK версии в каких файлах менять это ограничение?

Файл `eiskaltdcpp-gtk/ui/settingsdialog.ui`, элементы: `sharedUploadSlotsSpinButton` и `secondaryUploadSlots`. Вот только Glade (редактор ui-файлов для gtk-программ) -- просто кусок г*на, и после редактирования им ui-файл скорее всего сломается напрочь. Так что проще и надежнее этот xml-документ в текстовом редакторе править. Удачи...

**Comment by klug-pro** [comment]
Спасибо большое. Отредактировал в текстовом редакторе значения в файле `eiskaltdcpp-gtk/ui/settingsdialog.ui`:
было
```
<object class="GtkAdjustment" id="adjustment14">
    <property name="upper">100</property>
```
отредактировал
```
<object class="GtkAdjustment" id="adjustment14">
    <property name="upper">999</property>
```
Теперь количество слотов можно увеличивать до 999
