### ISSUE TITLE
Hub Menu

### ISSUE THREAD

**Issue by obifur** [eiskaltdcpp/eiskaltdcpp#355]
Many hubs provide individual "hub menus" (right click on the connected hub) with a bunch of infos/commands. 

QT-version:
All the entries are shown, but when clicking them, nothing happens.

GTK-Version:
There's no right click menu at all

---
Kubuntu 16.04 / EiskaltDC++ 2.2.10-155-g0fa9a73

**Comment by tehnick** [comment]
Hi. Try recent builds from our official PPA please. v2.2.10-179-g516a4492 or newer.
