### ISSUE TITLE
Eiskaltdc++-qt not giving any search results

### ISSUE THREAD

**Issue by gautamsreekumar** [eiskaltdcpp/eiskaltdcpp#358]
I had previously raised an issue (https://github.com/eiskaltdcpp/eiskaltdcpp/issues/348) regarding eiskaltdcpp crashing. I installed it recently by building it from the source. Now, it seems to be working fine, bu still am not able to search for anything. It simply shows no results. Anyone knows what I should do? I am on Active mode and the port number of TCP and UDP ports are 30000. It was 3000, but I changed it according a friend's solution.

**Comment by digital-idiot** [comment]
I'm facing this issue too. @gautamsreekumar, did you able to find any solution or workaround so far? It is very difficult to use it without the search function. I wonder why there is no response for this issue!

**Comment by gautamsreekumar** [comment]
@digital-idiot in my case the issue was the IP address masked by the router. I logged into the admin settings of the router and added virtual servers. In my router settings this was found in Forwarding section.

I added Service port and Internal port (same port) for various IP address that used to come up (dynamic IP I think, don't know a lot about it). Each time I connect to the LAN I check for the masked IP address and enter the corresponding port number to TCP port, UDP port in Preference->Connections

Usually the masked address comes out to be the same when I connect to router, but changes when I connect it via Wi-Fi.

Hope this solves your issue

**Comment by digital-idiot** [comment]
@gautamsreekumar  I've already set up port forwarding, but it didn't resolve the issue. By any chance TCP port and UDP port have to be same? I use different TCP port and UDP port, everything works except the search function.

**Comment by digital-idiot** [comment]
In my case, using same port for TCP and UDP solved the search related problem. Thanks to @gautamsreekumar

**Comment by gautamsreekumar** [comment]
Yeah. I forgot that part. You have to give the same port number for TCP and UDP. Sorry.
