### ISSUE TITLE
error while installing locally (error loading shared libraries: libeiskaltdcpp.so.2.3)

### ISSUE THREAD

**Issue by subhammridha** [eiskaltdcpp/eiskaltdcpp#361]
Hi,
Instead of installing  eiskaltdcpp globally, I tried to install it in my local user account.
For that, I specified `CMAKE_INSTALL_PREFIX` as `$HOME/.local`.

Installation was successfull. But after that, when I try to run it, it throws me the following error:

> eiskaltdcpp-qt: error while loading shared libraries: libeiskaltdcpp.so.2.3: cannot open shared object file: No such file or directory

If instead, I use `LD_LIBRARY_PATH` system variable pointing to `$HOME/.local/lib`, the software runs fine. But I do not wish to use the `LD_LIBRARY_PATH` variable as it slows the login process.

What do I do in order to fix this error?

**Comment by vovochka404** [comment]
You should understand, that eiskaltdcpp doesn't load libraries from some specified path. No, it's automaticaly searched only in system-defined library paths. You can see them in /etc/ld.so.conf.

So, you can add desired LD_LIBRARY_PATH to your .bashrc or .profile file. But more correct solution will be to edit your eiskaltdcpp.desktop file and specify LD_LIBRARY_PATH in it, like:

`Exec=env LD_LIBRARY_PATH=/home/user/.local/lib /home/user/.local/bin/eskaltdcpp`

**Comment by tehnick** [comment]
As @vovochka404 correctly mentioned, eiskaltdcpp is not designed for using non-standard library paths.
But with very few changes in build scripts you may compile program with enabled RPATH variable, which will do that you want.

**Comment by subhammridha** [comment]
OK. Thanks.
