### ISSUE TITLE
eiskaltdcpp-qt refuses to quit

### ISSUE THREAD

**Issue by digital-idiot** [eiskaltdcpp/eiskaltdcpp#363]
`Ctrl+q` just minimizes it to the system tray. Every time I had to kill it manually using `killall`.

**Comment by aneo78** [comment]
I will describe the problem in more detail. With Qt5.7.1, when the tray icon is enabled, the main window does not close. With Qt4.8, everything is fine, even if the icon is displayed.
Checked in distributions RFRemix 25, when assembling from the source code, as well as in RFRemix 26, when using a package from the repository.

**Comment by digital-idiot** [comment]
Hey, @aneo78 Why don't you **submit a pull request** and let the owner(s) decide to accept the pull request or not.

**Comment by aneo78** [comment]
Thanks @digital-idiot. Done.

**Comment by tehnick** [comment]
Fixed in a6849b6f49d29995ac6a77678dc9497b184c03ae
