### ISSUE TITLE
ERROR: A failure occurred in build().     Aborting... ==> ERROR: Makepkg was unable to build perl-test-use-ok.

### ISSUE THREAD

**Issue by K-ratos** [eiskaltdcpp/eiskaltdcpp#366]
Can't locate inc/Module/Package.pm in @INC (you may need to install the inc::Module::Package module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at Makefile.PL line 2.
BEGIN failed--compilation aborted at Makefile.PL line 2.

**Comment by skyhigh97** [comment]
Same error. Running Manjaro 17 on linux version 4.9.40-1

**Comment by sl1pkn07** [comment]
see the last comment of the perl-test-use-ok in [AUR]
