### ISSUE TITLE
A failure occurred in package_eiskaltdcpp-gtk()

### ISSUE THREAD

**Issue by D1mon** [eiskaltdcpp/eiskaltdcpp#368]
> /usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘struct dh_st’
>  typedef struct dh_st DH;
>                 ^~~~~
> /tmp/yaourt-tmp-dimon/aur-eiskaltdcpp-gtk/src/eiskaltdcpp-2.2.10/dcpp/CryptoManager.cpp:107:32: error: invalid use of incomplete type ‘struct dh_st’
>              if (!dh->p || !dh->g) {
>                                 ^
> In file included from /usr/include/openssl/crypto.h:31:0,
>                  from /usr/include/openssl/comp.h:16,
>                  from /usr/include/openssl/ssl.h:47,
>                  from /tmp/yaourt-tmp-dimon/aur-eiskaltdcpp-gtk/src/eiskaltdcpp-2.2.10/dcpp/SSL.h:19,
>                  from /tmp/yaourt-tmp-dimon/aur-eiskaltdcpp-gtk/src/eiskaltdcpp-2.2.10/dcpp/SSLSocket.h:23,
>                  from /tmp/yaourt-tmp-dimon/aur-eiskaltdcpp-gtk/src/eiskaltdcpp-2.2.10/dcpp/CryptoManager.h:24,
>                  from /tmp/yaourt-tmp-dimon/aur-eiskaltdcpp-gtk/src/eiskaltdcpp-2.2.10/dcpp/CryptoManager.cpp:20:
> /usr/include/openssl/ossl_typ.h:104:16: note: forward declaration of ‘struct dh_st’
>  typedef struct dh_st DH;
>                 ^~~~~
> make[2]: *** [dcpp/CMakeFiles/dcpp.dir/build.make:327: dcpp/CMakeFiles/dcpp.dir/CryptoManager.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:303: dcpp/CMakeFiles/dcpp.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2
> ==> ERROR: A failure occurred in package_eiskaltdcpp-gtk().
>     Aborting...
> ==> ERROR: Makepkg was unable to build eiskaltdcpp.
> ==> Restart building eiskaltdcpp-gtk ? [y/N]

OS: Manjaro (x64)

**Comment by tehnick** [comment]
Hi. It is already fixed in master branch (see commit https://github.com/eiskaltdcpp/eiskaltdcpp/commit/3b9c502ff5c98856d4f8fdb7ed3c6ef34448bfb7). You may backport patch from there to version 2.2.10 if you need.

**Comment by tehnick** [comment]
Hmm, it looks that this problem is in another place. I'll look on it more closely later.

**Comment by tehnick** [comment]
@D1mon  Could you attach a full build log? Also attach all extra patches against version 2.2.10, if they are used in you build.

**Comment by D1mon** [comment]
1) [pastebin](https://pastebin.com/Cm2B2ZFA)
2) не совсем понял. обычная установка "yaourt -S eiskaltdcpp-qt"

**Comment by tehnick** [comment]
2. Насколько я помню pkgbuild из AUR может использовать дополнительные патчи, которые применяются к оригинальным исходникам программы. Нужно будет посмотреть есть ли там что-нибудь для eiskaltdcpp-qt.

**Comment by tehnick** [comment]
Ну и вообще, лучше сперва какой-нибудь `eiskaltdcpp-qt-git` проверить. (Название может быть не точным, пока нет времени посмотреть.)

**Comment by D1mon** [comment]
я не сильно люблю частые обновления. поэтому не хочется ставить гит.
[PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=eiskaltdcpp)

**Comment by D1mon** [comment]
Раньше(~6 мес назад) я ставил eiskaltdcpp-qt. Все работало нормально.

**Comment by tehnick** [comment]
1) С текущим темпом разработки айскальта частых обновлений можно не опасалься.
2) Ну так сборочные зависимости обновились скорее всего.

**Comment by tehnick** [comment]
> PKGBUILD

Ссылка на гуглокод, сборка с Qt4, бекпортированных патчей не вижу (в пакетах для дебиана и убунту их целая пачка, например)... Этот PKGBUILD точно не протух? Какие версии openssl сейчас в системе?

**Comment by D1mon** [comment]
openssl 1.1.0.f-2

**Comment by D1mon** [comment]
[Прочитай комментарии](https://aur.archlinux.org/packages/eiskaltdcpp-qt)

**Comment by D1mon** [comment]
С первого раза не установилось, выскочила ошибка запустил пересборку проекта и все установилось.
PKGBUILD обновлен, ошибка устранена!
