### ISSUE TITLE
eiskalt-daemon no error messages

### ISSUE THREAD

**Issue by JuliusNmn** [eiskaltdcpp/eiskaltdcpp#369]
I'm trying to ise the eiskalt-cli. I can connect to a hub, I can list users, but  "list.download"  returns 1. I can view a users files with eiskalt-qt, and both use the same config dir. Does anyone have a hint to what could have gone wrong? 

Also, the eiskalt-daemon should be more verbose concerning errors. Returning 0 or 1 is not good.

**Comment by tehnick** [comment]
Yes, current protocol is very poor, but the chances that it will be changed are almost zero. Look to AirDC++ instead.
