### ISSUE TITLE
Невозможно открыть список файлов...

### ISSUE THREAD

**Issue by AlexMad666** [eiskaltdcpp/eiskaltdcpp#371]
Ошибка проявляется при размере файла больше 20-ти мегабайт (примерно).
Что интересно, на другой машине, где слабее процессор и меньше памяти нормально открываются списки файлов и по 100 мегабайт.
Настройки и там и там, вроде бы одинаковые. Единственно, что одна машина (которая маленькая и на которой все работает) работает под ubuntu-server по ssh, а на которой есть проблема - kubuntu-desktop.

**Comment by tehnick** [comment]
Нужна дополнительная информация о проблеме.
1) Версия программы.
2) Qt UI, GTK+ UI или оба варианта? Версии этих библиотек.
3) Как проявляется невозможность открытия файла?
4) В консоль что-нибудь выводится?
5) Этот же файл-лист открывается успешно в другой программе? (Если подсунуть настройки в LinuxDC++, например.)
5) Этот же файл-лист открывается успешно на другой машине? (Если скачать по сети или скопировать вручную и открыть из меню айскальта.)

**Comment by AlexMad666** [comment]
1. EiskaltDC++ 2.2.9 (stable)
Данная программа использует Qt версии 4.8.7.
Версии одинаковы на обоих машинах.
2. Точно знаю, что проявляется в Qt варианте при попытке согласовать очередь.
3. При попытке согласовать очередь файл скачивается, но в строке состояния появляется надпись Невозможно открыть список файлов: </home/alexmad/.local/share/eiskaltdc++/FileLists/Shadow.IKZO57KM2JNTMPRA7B2R4ZUQJR5X3IBN3PP3NYI.xml.bz2>
4. В лог выводится тоже самое. В консоли ничего нет.
5. Другой программы, к сожалению сейчас нет, но при попытке открыть скачанный файл появляется такая ошибка: Ошибка виджета просмотра списка файлов: 104857521: Greater than maximum allowed size. В консоли опять тихо.
6. На другой машине этот самый файл прекрасно открывается.

Я понимаю, что у меня где-то в системе нужно просто поправить максимальный размер файла. Вопрос только где его искать.

**Comment by AlexMad666** [comment]
Дополню. Поставил на проблемную машину LinuxDC++ - он скачанный файл открыл без вопросов.

**Comment by pavel-pimenov** [comment]
Greater than maximum allowed size
оно гуглится прям тут:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/52af555638f7b1b4baa58b43be75985fcf82760e/dcpp/SimpleXMLReader.cpp#L558

**Comment by pavel-pimenov** [comment]
@AlexMad666  вам нужно в конфиге поправить параметр MaxFilelistSize
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/52af555638f7b1b4baa58b43be75985fcf82760e/dcpp/DirectoryListing.cpp#L134

ну и скажите какой он у вас стоял?

**Comment by AlexMad666** [comment]
Спасибо. Стоял 100.
Поменял на 1000, все заработало.
Теперь ещё вопрос: а где в настройках этот параметр? Или он только в конфиге правится?

**Comment by pavel-pimenov** [comment]
Визуально не могу показать скрин, но по коду это в закладке advanced должно где-то быть
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/52af555638f7b1b4baa58b43be75985fcf82760e/eiskaltdcpp-gtk/src/settingsdialog.cc#L520
и значение 100 не дефолтное (4*1024) т.е. кто-то его подвигал.
Возможно для исключения такого бага имеет смысл сделать лимит 
чтобы пользователь не мог задавать заведомо мелкие значения.

**Comment by tehnick** [comment]
@pavel-pimenov Спасибо.

Кстати, по приведенной ссылке -- GTK+ UI, а не Qt UI.

**Comment by pavel-pimenov** [comment]
PR кривой получился - захватил старые мержи.
я так и не научился чинить этот базе безе пересоздания форка.
