### ISSUE TITLE
macOS: question about settings

### ISSUE THREAD

**Issue by Tata55** [eiskaltdcpp/eiskaltdcpp#376]
I used DC++ on a PC some years ago. Now, working with MAC I have found and installed the Eiskaltdc++. My account has been found immediately and shared folders have been actualized. But that's about all.
I can't set slots, I can see the hubs but can't browse any particular  sources. Simply, I can't use the app as with my PC before.
Is there any manual for correct setting available?
Can you answer to info@cmsimple.sk?
Thanks in advance.

**Comment by tehnick** [comment]
Hi,

Please try the last build (`2.2.10-228-macOS10.11`) of EiskaltDC++ from here:
https://sourceforge.net/projects/eiskaltdcpp/files/macOS/devel/
Or you [may install it](https://github.com/Homebrew/homebrew-cask/pull/51111) using homebrew.

Despite this version looks less than previous, it is more recent. Yes, we have used very strange versioning scheme for development builds in the past... See short discussion with homebrew maintainer: https://github.com/Homebrew/homebrew-cask/pull/51111

> I can't set slots, I can see the hubs but can't browse any particular sources. Simply, I can't use the app as with my PC before.

1) Have you set up your username in Preferences dialog?
2) Which type of connection do you use? (Active mode, Firewall with UPnP or Passive mode.)

> Is there any manual for correct setting available?

Nope. But it should not be difficult in setup... There are only few obligated steps:
1) Set nickname.
2) Choose network connection type.
3) Connect to any hub.

And all should work.

**Comment by tehnick** [comment]
> I use phone line connection with Down-Up 37Mbit/s – 3Mbit/s. I tried all possible settings (Active mode, Firewall with UPnP or Passive mode.) with no change.

Hmm, last time I have faced with this type of network connection very very long time ago...

If your provider filters UDP packages the search function may not work in DC clients, but p2p interactions with other users should work in any case. Try to download users file lists and any files from these file lists.

Also I would recommend to set up "Passive mode" in connection settings and try to use EiskaltDC++ with it at least few days. Just do usual user's activity and observe that happens. If program will not work as expected, then it not suitable in your case, unfortunately.

**Comment by Tata55** [comment]
Some years ago, I worked with Windows7 and the DC++ worked fine. Later – switching to MAC – it worked as well. I have not used it for about 4 years and installed it just now. I’ve been recognized in all known hubs immediately, but without any possibility to search in any user shared files.

 

 

PaedDr. Martin Sereday
Štúrova 2
053 04 Spišské Podhradie
SLOVAKIA
+421 907 974 541
www.cmsimple.sk    |  Proroctvá hopiov
