### ISSUE TITLE
Daemon: keeps the old search results

### ISSUE THREAD

**Issue by kuzmos** [eiskaltdcpp/eiskaltdcpp#377]
When I run multiple searches, the previous search results stay in the window no matter what I do. I tried to access eiskaltdcpp-webui url by Ctrl-F5, anonymous mode, different browser - all search results stay till I restart the daemon.

Daemon OS: FreeBSD (Freenas jail)

 % uname -a
... FreeBSD 11.1-STABLE

**Comment by tehnick** [comment]
Fixed in 8e4e530d9eba59b4cf4b6e7396b5a4e0f14c8349
