### ISSUE TITLE
macOS: Total upload/download resets on quitting app

### ISSUE THREAD

**Issue by dhani13** [eiskaltdcpp/eiskaltdcpp#379]
On macOS, the Total Up and Total Down values (visible in menu bar, About EiskaltDC++) are not modified correctly. Specifically, both values are changed to the higher of the two when the app is closed/ and opened again. Consequently, the Ratio value is always 1.000 whenever the app is opened. All 3 values can change based on transfers when the app is open, but they are always reset when it is closed.

**Comment by tehnick** [comment]
Hi, I could not reproduce this bug in my system. What version of EiskaltDC++ do you use? Please try the latest version (2.2.10-228-macOS10.11) and check if this bug still present there.

**Comment by dhani13** [comment]
Sorry for the late reply.

The version of EiskaltDC++ is 2.3.0 (8c41579). The macOS version is 10.13.6
<img width="491" alt="screen shot 2018-08-30 at 09 34 56" src="https://user-images.githubusercontent.com/21221083/44828948-d9ad6b80-ac37-11e8-8791-e4534995b067.png">
To be clear about the bug, these are the values I'm talking about. I've not installed EiskaltDC++ from source or from Homebrew, but from a .dmg file downloaded from https://sourceforge.net/projects/eiskaltdcpp/

**Comment by tehnick** [comment]
> The version of EiskaltDC++ is 2.3.0 (8c41579).

It is extremely old build of program, please use version `2.2.10-228-macOS10.11` instead. Despite this version looks less than previous, it is more recent. Yes, we have used very strange versioning scheme for development builds in the past... See short discussion with homebrew maintainer: https://github.com/Homebrew/homebrew-cask/pull/51111

> I've not installed EiskaltDC++ from source or from Homebrew, but from a .dmg file downloaded from https://sourceforge.net/projects/eiskaltdcpp/

As you may see at https://github.com/Homebrew/homebrew-cask/pull/51279 Homebrew now uses the correct link to EiskaltDC++ app bundle, so there is no difference in which way you will install the program.
