### ISSUE TITLE
macOS: unable to download binary files, only file lists and small files

### ISSUE THREAD

**Issue by ebernet** [eiskaltdcpp/eiskaltdcpp#381]
I am having an issue with EiskaltDC++. I can download .txt, .md5, .png, .ffp, .sfv, file lists, but for the life of me I cannot download large files, like .mkv, mp4, .flac, .shn, etc.
People can get any files from me. I see no errors in the queue. No indication of any errors, but the download is 0. This is whether I am public or private hubs. I have a firewall wit the ports forwarded. I have tried everything to no avail, I just cannot figure out what is going on. My PC running ApexDC++ does not have this issue. I am on High Sierra (also tried on Mojave) and I have 0 problems with Bit Torrent clients. Is anyone out there able to help me?

**Comment by tehnick** [comment]
Which version of EiskaltDC++ are you using?

Could you try to set up a passive connection mode in settings and test program with it for a while?

**Comment by ebernet** [comment]
2.2.10-196-g860a0bc5
yeah, tried passive. Trying again now

**Comment by ebernet** [comment]
How many hours should I leave it on passive with 0 downloads lol?

**Comment by tehnick** [comment]
> 2.2.10-196-g860a0bc5

There is a newer version for macOS on SF.

> How many hours should I leave it on passive with 0 downloads lol?

If I understand correctly this did not solve problem. It is a pity...

Have you checked more simple possible reasons of problem? For example, your user should have write access to download directory and enough free spaces on this disk partition.

I have just re-checked downloading of big files using passive connection and connection via UPnP: in both cases files have been downloaded successfully.

(Tested on my laptop with macOS 10.13.6.)

**Comment by ebernet** [comment]
That would not explain the .png and small files downloading. Plus I have write access…
Will try the new version. Do I need to build it?
Eytan

**Comment by tehnick** [comment]
> Do I need to build it?

Of course no. If you use `homebrew` project then just run:
```
brew update
brew cask install eiskaltdcpp
```
If not then just download `dmg` file and install it manually:
https://sourceforge.net/projects/eiskaltdcpp/files/macOS/devel/

**Comment by ebernet** [comment]
I see a 228, but that is for 10.11…
Should I try the version for older OSs?
I tried the 2.2.3 one as well…
Eytan

**Comment by tehnick** [comment]
> That would not explain the .png and small files downloading.

Exactly! It is puzzled me the most.

**Comment by tehnick** [comment]
> but that is for 10.11…

It is for macOS 10.11 and newer.

**Comment by ebernet** [comment]
I see the same versions there. Are you asking me to install the EiskaltDC++-2.2.10-228-macOS10.11-x86_64.dmg <https://sourceforge.net/projects/eiskaltdcpp/files/macOS/devel/EiskaltDC%2B%2B-2.2.10-228-macOS10.11-x86_64.dmg/download>?
I assumed that was for macOS 10.11, not 10.13
Eytan

**Comment by tehnick** [comment]
> I tried the 2.2.3 one as well…

It is extremely old and have many bugs, which we were not aware at that time because we did not have a developer with macOS...

Also that version do not support of TLS 1.2 and few more important features.

**Comment by tehnick** [comment]
> I assumed that was for macOS 10.11, not 10.13

macOS supports launching of applications built for older versions of system, but does not support launching of applications built for newer versions of system. So for simplifying life of program users we have to build app bundles for older versions of macOS for not forcing them to update their systems. I supposed it is obvious...

**Comment by ebernet** [comment]
Okay. I am trying the 10.11+ version. No difference

**Comment by ebernet** [comment]
FYI this was because I had insufficient space. An error message of some kind would be appropriate probably. Thanks I will grab latest
Eytan

**Comment by tehnick** [comment]
> FYI this was because I had insufficient space.

Ok.

> An error message of some kind would be appropriate probably.

Yes, but this is another issue.
