### ISSUE TITLE
[Qt] Enter key in chat window not working

### ISSUE THREAD

**Issue by KalleKulag** [eiskaltdcpp/eiskaltdcpp#390]
After the last git pull the enter key just adding new lines making the windows taller not sending any text in chat window.
eiskalt-qt on fedora 29

**Comment by tehnick** [comment]
Use Ctrl+Enter or disable option "Use Ctrl+Enter to send messages" in Preferences dialog on tab "GUI".

**Comment by tehnick** [comment]
Hmm, unexpectedly only Ctrl+Enter and Shift+Enter works. I'll re-check source code.
