### ISSUE TITLE
Request insertion of new hublist xml.bz2 on Public Hubs

### ISSUE THREAD

**Issue by skylinkdc** [eiskaltdcpp/eiskaltdcpp#392]
Request insertion of new hublist xml.bz2 on Public Hubs   https://dchublist.biz/hublist.xml.bz2

**Comment by tehnick** [comment]
bc8f9e3beda1c6c064a33e46be49d72afb3d7c43
ee23a734704041adb46b4f8adf0ef5b63dc95596
