### ISSUE TITLE
ADC: Wrong application version is sent

### ISSUE THREAD

**Issue by dennwc** [eiskaltdcpp/eiskaltdcpp#395]
**Steps to reproduce:**
1) Open "Debug Console", enable "HUB_OUT".
2) Connect to any ADC hub.
3) Check debug console.

**Expected:**
```
BINF ... APEiskaltDC++ VE2.2.10
```
(application name in `AP` field and version in `VE` field)

**Observed:**
```
BINF ... VEEiskaltDC++\s2.2.10
```
(both fields concatenated and sent as `VE` field)

**Comment by tehnick** [comment]
Hmm, which version of program do you use?

**Comment by tehnick** [comment]
I have not looked to debug console yet, but in the list of users on hubs version of program looks fine.

**Comment by tehnick** [comment]
(I use builds from `work` branch now.)

**Comment by tehnick** [comment]
> Observed:
> BINF ... VEEiskaltDC++\s2.2.10

Hmm, it is confirmed. But it worked for years without any issues...

I'll look in DC++ code, of course, for comparing difference with our core.
But I am not sure how this is important and urgently.

**Comment by dennwc** [comment]
The reason it works is mostly that clients usually append those two fields into NMDC-like tag when displaying the user list. Still, it's incorrect from the protocol perspective. For example, hubs are forced to work around it to get correct stats for app version distribution.

It's not critical of course, but it should not be hard to fix either.

**Comment by tehnick** [comment]
Try build from `master` branch.

**Comment by tehnick** [comment]
9180ecd broke fake client ID feature. It should be rewritten.

**Comment by tehnick** [comment]
e1aca6c02008397d46f7c7db7d9898b632844385
96f8fe00dfb94c6cb236abe3d46134890e294dec
