### ISSUE TITLE
macOS: problem with connection settings

### ISSUE THREAD

**Issue by LumpyScherbatsky** [eiskaltdcpp/eiskaltdcpp#401]
Dear community,
unfortunately I can not use DC++ anymore. Some time ago it worked pretty well, but now it always just shows "Not listening for connections - please restart Eiskalt DC++". I did and I also reinstalled everything. It shows that I am connected, but when I want to browse some files, it is not working! Can you help me? Thank you very much in advance!

**Comment by tehnick** [comment]
This is a bug tracker, but not a communication channel with community...

> I did and I also reinstalled everything.

Re-installation should not help in anything. Your problem is in connection settings.

> Not listening for connections - please restart Eiskalt DC++

This information is not enough.

What operation system do you use?
What version of EiskaltDC++ do you use?
What type of network connection do you use?
Etc..

Also screenshot of Connection tab in Preferences dialog may be helpful a bit.

**Comment by LumpyScherbatsky** [comment]
Hi tehnick,
sorry, my mistake!
I am using macOS Mojave, the version of DC++ is 2.2.10 (core version: 0.785 (modified)) and the type of network is the Passive Mode. I am living in a students house, so there is just one nut (my roommate said I should tell you this). Do you need more information?

![Bildschirmfoto 2019-04-23 um 17 57 53](https://user-images.githubusercontent.com/49750085/56597516-ee89a580-65f2-11e9-9b7e-5e7026a88007.png)

**Comment by tehnick** [comment]
> I am using macOS Mojave

Ok. It this system all program settings are stored in `/Users/<username>/.config/eiskaltdc++/`. You may remove or rename this directory to reset program settings and setup everything from scratch.

> the version of DC++ is 2.2.10

This is not full version of program. Full version should look like `2.2.10-531-g6c420aac` (in your case version from app bundle name should be enough, i.e: `2.2.10-531`).

> the type of network is the Passive Mode.

Hmm, this mode of connection is the least demanding in configuration and everything should work out of the box.

Ok, lets check few other possible problems:

* Check that you have set a nick name on the first tab of Preferences dialog.
* Check messages from hub bots just after connection. Some hubs are configured in such way that they do not allow search requests from unregistered users or from users with too small share.

> I am living in a students house, so there is just one nut (my roommate said I should tell you this).

Ok, Passive Mode should be the right choice for you.

> Do you need more information?

I don't know yet. Check recommendations above first.

**Comment by tehnick** [comment]
Any progress with resolving of problem?

**Comment by LumpyScherbatsky** [comment]
No unfortunately not. Except from removing/renaming the directory (because I could not find it), I tried everything you said. I have the newest version of DC++ (EiskaltDC++ 2.2.10-531-g6c420aac), I have a nickname and I have uploaded enough to share. Otherwise it is not even possible to connect at our place.

**Comment by tehnick** [comment]
> Except from removing/renaming the directory (because I could not find it)

Unfortunately macbook is not near me now, and I do not remember how to open non-standard paths in it... But you may easily delete this directory from command line of Terminal.

To look at current list of files in config directory:
```
ls -alp ~/.config/eiskaltdc++/
```

For removing this directory with all files in it:
```
rm -r ~/.config/eiskaltdc++/
```

> Otherwise it is not even possible to connect at our place.

I suppose that you are trying to connect to some hub in your local campus network. Am I right?
Could you show screenshot with first messages in hub groupchat just after connection to it?

Next. Could you connect to popular hubs from public hub list? Try to connect to few of them simultaneously. If you connected to them without problems try to search anything popular.

**Comment by tehnick** [comment]
Also could you show the URL of you hub which you are trying to connect to?
If not then write at least the URL schema with you use. For example:
```
dchub://<hub-name>
dchub://<ip-address>
dchub://<ip-address>:<port>
nmdcs://<ip-address>:<port>
adc://<hub-name>:411
adcs://<ip-address>:412
etc.
```

**Comment by LumpyScherbatsky** [comment]
Thanks for your support. Sure I will send you everything you asked for when I am home again tomorrow evening.

**Comment by LumpyScherbatsky** [comment]
Hi, after removing the directory it worked now! Thanks a lot!

**Comment by tehnick** [comment]
Ok.
