### ISSUE TITLE
Request: Add a new hublist

### ISSUE THREAD

**Issue by Kcchouette** [eiskaltdcpp/eiskaltdcpp#405]
Hello

Thank you for eiskalt!  
Can you insert the xml from the hublist https://dcnf.github.io/Hublist/?

 - xml: https://dcnf.github.io/Hublist/hublist.xml
 - xml.bz2: https://dcnf.github.io/Hublist/hublist.xml.bz2

I hope theses links are fully compatible with your software, they are for the moment not integrate in a DC client.

Thank you in advance.

**Comment by tehnick** [comment]
Why xml document includes address http://hublist.eu ?
```
<Hub ASN="" Address="http://hublist.eu" Bots="" Country="Ukraine" Description="# Powered by NLight DC++ Ukraine #" Email="" Encoding="" Failover="" Infected="" Maxhubs="" Maxusers="" Minshare="0" Minslots="" Name="# (UAPEER.EU/HUBLIST.EU) #" Operators="" Rating="5.0" Reliability="" Shared="" Software="" Status="" Users="0" Website=""/>
```

**Comment by tehnick** [comment]
Also there is no any nmdcs hub.

**Comment by tehnick** [comment]
Some adc hubs from your list are unavailable now.

**Comment by Kcchouette** [comment]
Thank you for remarks, I'll fix the first one and second one:

 - > Why xml document includes address http://hublist.eu ?

Because it's inside the hublist from hublist.eu I'll fix that on my side, and reporting later for the hublist owner


 - > Also there are no nmdcs hubs in your list.

Indeed, but it's somewhat coming :) https://github.com/direct-connect/go-dcpp/issues/93

- > Some adc(s) hubs from your list are unavailable now.

As I'm doing update weekly, and not every hour like other hublist, It's why I don't have the very last accurate online/offline mode.
Sadly It's not on on my top priority on the moment, to run/commit every hour a xml file. If you have automatic solution, do not hesitate to contact me, even using the [bug tacker of this project](https://github.com/DCNF/Hublist/issues).
