### ISSUE TITLE
Softlinked directories and mounted drives do not appear in Sharing browser

### ISSUE THREAD

**Issue by patrickvacek** [eiskaltdcpp/eiskaltdcpp#408]
Most of the directories I want to share are on a separate drive that I keep mounted. I also have a softlink in my home directory that points at a directory in that drive. Neither the mountpoint nor the softlink appear in the Sharing browser. I tried manually editing the config file (`DCPlusPlus.xml`) to add the paths, and then they show up in the Sharing browser, but nothing is found in them, even if I force a rehash.

How can I convince EiskaltDC++ to accept my mounted drive and/or softlinks?

I'm using EiskaltDC++ 2.2.10-631-g7bd2f5d6, installed via snap on Ubuntu 19.04.

**Comment by tehnick** [comment]
As for `snap`, I do not know where this should be configured. I have read somewhere that user should explicitly allow access to specific directories for applications launched from its sandbox.

As for EiskaltDC++ settings, see:
![Screenshot_20190610_235042](https://user-images.githubusercontent.com/441190/59225958-b22dfb00-8bda-11e9-8681-e7c8dd11c5df.png)

**Comment by patrickvacek** [comment]
> As for `snap`, I do not know where this should be configured.

I was editing `~/snap/eiskaltdcpp/common/.eiskaltdc++/DCPlusPlus.xml`, although I assume I shouldn't have to manually edit that file. Besides, that didn't really work. The directories are then listed, but their size is 0 B, which is not accurate.

> I have read somewhere that user should explicitly allow access to specific directories for applications launched from its sandbox.

That is interesting, but it is odd that EiskaltDC++ seems to be able to access any system directory it wants.

> As for EiskaltDC++ settings, see:

Good call with the "Follow symlinks", but that unfortunately doesn't seem to change anything.

**Comment by patrickvacek** [comment]
> I have read somewhere that user should explicitly allow access to specific directories for applications launched from its sandbox.

Holy crap, it turns out you were right. See, for example, https://askubuntu.com/questions/1033344/how-to-give-snaps-access-to-somedir. I've found other people complaining about the same issue for EiskaltDC++ in the Ubuntu Software catalog, too. Sorry for the bother, and thanks for the tip. Installing via apt solves the problem.

**Comment by tehnick** [comment]
@dennwc What we may do to improve situation with `snap` from our side?
