### ISSUE TITLE
[pango issue] Incorrect include path leads to hb.h: No such file or directory 

### ISSUE THREAD

**Issue by ValdikSS** [eiskaltdcpp/eiskaltdcpp#413]
EiskaltDC++ does not compile anymore with new pango on ArchLinux.
https://bugs.archlinux.org/task/63460
https://gitlab.gnome.org/GNOME/pango/issues/387
EiskaltDC++ should use cflags provided by `pkg-config --cflags pango`.

**Comment by JandeGrootDuracom** [comment]
The problem is in findGtk3.cmake which included hardcoded include paths:
# If these ever change, things will break.

Pango requires harfbuzz since 1.44, so things will break.

**Comment by Vascom** [comment]
We already have problems in Fedora https://bugzilla.redhat.com/show_bug.cgi?id=1741077

**Comment by tehnick** [comment]
As for builds with GTK+ 2.x you need to modify system `FindGTK2.cmake` from `cmake` package. For example:
```diff
--- /usr/share/cmake-3.15/Modules/FindGTK2.cmake.orig   2019-09-22 14:08:49.865583839 +0000
+++ /usr/share/cmake-3.15/Modules/FindGTK2.cmake        2019-09-22 14:12:08.848701711 +0000
@@ -259,6 +259,7 @@
         gtkmm-2.4
         libglade-2.0
         libglademm-2.4
+        harfbuzz
         pango-1.0
         pangomm-1.4
         sigc++-2.0
@@ -707,6 +708,8 @@
         _GTK2_FIND_LIBRARY    (CAIRO cairo false false)
         _GTK2_ADD_TARGET      (CAIRO)
 
+        _GTK2_FIND_INCLUDE_DIR(HARFBUZZ hb.h)
+
         _GTK2_FIND_INCLUDE_DIR(PANGO pango/pango.h)
         _GTK2_FIND_LIBRARY    (PANGO pango false true)
         _GTK2_ADD_TARGET      (PANGO GTK2_DEPENDS gobject glib)
```
