### ISSUE TITLE
Failed build with pango 1.44.3

### ISSUE THREAD

**Issue by Vascom** [eiskaltdcpp/eiskaltdcpp#414]
In Fedora we have updated pango to 1.44.3. And eiskaltdcpp failed build with it.
Seems that eiskaltdcpp does not use pango pkg-config module for retrieving pango CFLAGS.

Also please see https://bugzilla.redhat.com/show_bug.cgi?id=1741077

**Comment by ppisar** [comment]
This seems to be  a duplicate of issue #413.

**Comment by Vascom** [comment]
Yes.
