### ISSUE TITLE
Hub commands over right-click menu are not working in Luadch

### ISSUE THREAD

**Issue by Neolo** [eiskaltdcpp/eiskaltdcpp#416]
Hub commands over right-click menu are not working in Luadch. No reaction. But other clients like apex dc are work with luadch just fine.

**Comment by tehnick** [comment]
Sorry but what is "Luadch"? I have just tested hub commands in popular public hubs and all works fine.

Also you have not specified:
1) Which version of program do you use?
2) In which operation system?
3) If this is program in Linux, which UI do you use? There are Qt based and GTK+ based user interfaces.

**Comment by tehnick** [comment]
Could you give an example of any public hub controlled by `Luadch` hub software?

**Comment by Neolo** [comment]
> Could you give an example of any public hub controlled by `Luadch` hub software?

adc://toloka.uapeer.eu:511

**Comment by tehnick** [comment]
> adc://toloka.uapeer.eu:511

Unfortunately I cannot connect to this address.

```
$ ping -c10 toloka.uapeer.eu
PING toloka.uapeer.eu (31.3.251.150): 56 data bytes
--- toloka.uapeer.eu ping statistics ---
10 packets transmitted, 0 packets received, 100% packet loss
```

Packages are filtered somewhere in UK:
```
$ traceroute toloka.uapeer.eu
traceroute to toloka.uapeer.eu (31.3.251.150), 30 hops max, 60 byte packets
...
 9  1046.zone.6.r.dc10.redstation.co.uk (185.20.96.174)  68.114 ms  68.278 ms  68.252 ms
10  * * *
...
```

**Comment by Neolo** [comment]
Check now

**Comment by tehnick** [comment]
Connected successfully. Thanks!

**Comment by tehnick** [comment]
Yep, I see your problem now: after choosing of any item from "Hub Menu" hub software resets connection:
```
[15:18:07] *  Fail: Connection closed...
```

**Comment by Neolo** [comment]
That happens only with Eiskalt, not other dc clients. Apparently connection is getting closed due to invalid client's commands sent.

**Comment by tehnick** [comment]
Ok, I see. I'll debug this a bit later.

**Comment by tehnick** [comment]
Fixed in version `v2.4.0-9-gaaf2f4bb`. I'll make devel builds tomorrow.

This bug was present since first versions of EiskaltDC++ as I see and nobody reported about it. Fix is very simple, but I spended a lot of time to find the root of problem...

Thanks for a bug report!

**Comment by Neolo** [comment]
Thanks. It took a year for you to read this ticket =)

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.1 is released.

**Comment by Neolo** [comment]
Thanks. There is some weird CPU issue on MacOS. When Eiskalt is running for 24+ hours, it starts consuming 100% of the cpu time until restarted.

**Comment by tehnick** [comment]
It is very strange. On my MacBook Air (2015) with macOS 11.1 (Big Sur) EiskaltDC++ usually works without restarts during weeks. And I have not noticed any issues.

**Comment by Neolo** [comment]
You have to have share on it, over SMB drive

**Comment by tehnick** [comment]
> You have to have share on it

It is with non-empty share. And sometimes even with non-empty downloads queue...

> over SMB drive

Could you explain what is this and how to check it? Please open another bug report with details.

**Comment by Neolo** [comment]
Samba

**Comment by Neolo** [comment]
There is no more details. It persists across all versions, in about 24h+. Quite unusable.

**Comment by tehnick** [comment]
> Samba

I do not know how to use samba in macOS and I do not have any samba resources in my local network.

As far as your use case, it is too specific and don't affects many users I do not think I'll find time for investigations.

> There is no more details. It persists across all versions, in about 24h+.

Currently there are too few info from you.

How often files in this samba share are updated? How often timestamps of these files are changed?

Try to disable automatic updated of share in EiskaltDC++. Probably this will help.
