### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by Sopor** [eiskaltdcpp/eiskaltdcpp#418]
Will there be a new release of EiskaltDC++ soon? It was 4 years ago it was announced that a new version was going to be released... The only thing that seems to be updated are the language files.

**Comment by tehnick** [comment]
> Will there be a new release of EiskaltDC++ soon?

Yes, I hope so.

> The only thing that seems to be updated are the language files.

No, there were a lot of changes in different parts of program since last git tag. Incomplete changelog is one of reasons of delaying the new release...

**Comment by raspher** [comment]
Please create milestone and a tasklist what is needed for next release

**Comment by megadr01d** [comment]
Will version 2.2.10+ support only macOS 10.13+? I'm stuck on 10.11 (El Capitan) forever.

**Comment by tehnick** [comment]
> Will version 2.2.10+ support only macOS 10.13+? I'm stuck on 10.11 (El Capitan) forever.

If you are talking about official builds on SF then answer is yes, unfortunately. Homebrew developers dropped support of macOS older than 10.13. But if you can build program from sources then it should be possible even for OS X 10.9 Mavericks or even older.

**Comment by tehnick** [comment]
> Please create milestone and a tasklist what is needed for next release

I have already prepared AppImage packages:
https://sourceforge.net/projects/eiskaltdcpp/files/Linux/devel/

So only two tasks have left to be done before `2.4.0` release:
https://github.com/eiskaltdcpp/eiskaltdcpp/milestone/2

**Comment by tehnick** [comment]
> The only thing that seems to be updated are the language files.

After this assertion I was interested enough to look at the list of changes since the beginning of 2017:
`git diff -w --ignore-blank-lines --stat 0fa9a730 | grep -v translations/ | grep -v po/ | grep -v data/ | grep -v \.png | grep -v \.svg | grep -v \.desktop| grep -v upnp/ | grep -v json/ | tee ../tmp.log`

Summary:
```
1649 files changed, 70059 insertions(+), 92195 deletions(-)
```

Full list: https://susepaste.org/74617731

Work is done slowly but it is done...

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.0 is released.
