### ISSUE TITLE
macOS: broken build 2.2.10-644-macOS10.12: do not work in macOS 10.13 and older

### ISSUE THREAD

**Issue by JohnP246** [eiskaltdcpp/eiskaltdcpp#421]
Hi, I'm unable to open the app since the November security update. I have Mac High Sierra 10.13.6. When I double click to open the app, it simply doesn't open. Thanks!

**Comment by tehnick** [comment]
1) Have you tried to reinstall program after update of macOS?
2) Which versions of EiskaltDC++ have you tried?

**Comment by JohnP246** [comment]
Thanks for your reply! Yes, I tried reinstalling the app with the latest version.

**Comment by tehnick** [comment]
Please write explicit versions which you have tried. For example, these versions were build with different versions of XCode in different versions of macOS and may work differently:
* 2.2.10-644-macOS10.12
* 2.2.10-631-macOS10.12

**Comment by JohnP246** [comment]
Thank you--I was using 2.2.10-644-macOS10.12. Actually, I just tried 2.2.10-631-macOS10.12 and it worked! So I'm not sure why the newer one isn't working.

**Comment by tehnick** [comment]
Ok, thanks for info.

**Comment by tehnick** [comment]
Try `EiskaltDC++-2.2.10-650-macOS10.13-x86_64.dmg`.
