### ISSUE TITLE
Unable to uninstall completely in Mac OS Catalina

### ISSUE THREAD

**Issue by anuiitbgithub** [eiskaltdcpp/eiskaltdcpp#424]
Using EiskaltDC++ 2.2.10-645-g64546ad3. 

The components that can be found for deletion are:
the app binary,
the directory ~/Library/Saved ApplicationState/com.github.eiskaltdcpp.savedState and 
the directory /var/folders/5m/xchmsqp10k97...com.github.eiskaltdcpp

Deleting these does not get rid of saved state/preferences. After reinstall the app starts from previous state.

Also, on a Mac the files hashindex.xml and hashdadat.dat do not show up via search.

**Comment by tehnick** [comment]
EiskaltDC++ uses classic paths in all *nix systems:
```
~/.config/eiskaltdc++/
~/.local/share/eiskaltdc++/
```

In macOS they should point to:
```
/Users/<user>/.config/eiskaltdc++
/Users/<user>/.local/share/eiskaltdc++/
```
