### ISSUE TITLE
No option to share data 

### ISSUE THREAD

**Issue by fireballpoint1** [eiskaltdcpp/eiskaltdcpp#425]
There is no option to add a share folder and the non-simple view is unclickable 
![image](https://user-images.githubusercontent.com/16238837/72048631-38cac800-32e3-11ea-8655-ebda347fa55b.png)
![image](https://user-images.githubusercontent.com/16238837/72048648-408a6c80-32e3-11ea-9057-7bc150de6e5d.png)

**Comment by tehnick** [comment]
> There is no option to add a share folder

See context menu by right click on the list of shared folders.

> non-simple view is unclickable

Unwrap folders tree to your home directory and re-check checkboxes on folders in it.

**Comment by tehnick** [comment]
Also is this version of EiskaltDC++ from repository or from snap-package? In the later case program have additional limitations of access to filesystem.

**Comment by fireballpoint1** [comment]
@tehnick this was from the snap-package
