### ISSUE TITLE
doesn't work without specifying a port in the hub address nmdcs://

### ISSUE THREAD

**Issue by 1o1o1** [eiskaltdcpp/eiskaltdcpp#426]
doesn't work without specifying a port in the hub address  " nmdcs:// "     https://ibb.co/Jqhxpn4
if the port is specified, nmdcs://dchub.in.ua:411, then everything works ;)  https://ibb.co/bbW9J22

не работает без указания порта ;) 
как только порт прописал nmdcs://dchub.in.ua:411 все заработало)
знаю по умолчанию тока для dchub:// порт не нада) 
но лучше бы чтобы подставляло и для adc(s):// nmdc(s)://

**Comment by tehnick** [comment]
Yes, and this is intentional behavior because there is no standard or generally accepted default port for connection to `nmdcs` hubs.

**Comment by tehnick** [comment]
Standard ports are defined here:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/v2.4.0/dcpp/Util.cpp#L655
