### ISSUE TITLE
MacOS problems connection on Catalina

### ISSUE THREAD

**Issue by MaxD72** [eiskaltdcpp/eiskaltdcpp#434]
Good afternoon, my name is Max and I'm new here, nut by long time I'm using DC++ and unfortunately on Catalina my old app doesn't work so I got Eikalt, 
![Eiskalt](https://user-images.githubusercontent.com/63414812/78916153-54ce3900-7a8d-11ea-85ce-c9fd01e5e9d7.jpg)
as you can see from the picture my EiskaltDC++ version is 2.2.10-650-gf76c6144 and I've some trobles to connect in active mode. I switched off VPN and Little Snitch since I've opened the door on my router FRITZ!Box, but I can't connect not even to download the HubList, could someone tell what is wrong setted please?
Thnak you so much.

**Comment by tehnick** [comment]
1) You are trying to connect to absolutely wrong hub addresses. Hublist URL != URL of hub.
2) How are you connected to network? (Direct connection via ethernet, via wi-fi router, etc.) Do you have static IPv4 address? If no, use passive mode.
3) Do not forget to set username in settings.

**Comment by MaxD72** [comment]
I'm connected to network  via ethernet and I've a static IPv4 address, but the hub addresses ita was correct, I'll try to search a new one

**Comment by tehnick** [comment]
> I'm connected to network via ethernet and I've a static IPv4 address

Great! Then active mode should work fine for you.

> but the hub addresses ita was correct

No, it was not. Let's look at your screenshot again:
![78916153-54ce3900-7a8d-11ea-85ce-c9fd01e5e9d7](https://user-images.githubusercontent.com/441190/78938183-72fe5e00-7aba-11ea-9c4e-457d1a8a7a71.jpg)

These URLs are not hub URLs. Correct URLs should look like these:
```
dchub://example.com
dchub://example.com:411
nmdcs://example.com:411
adc://example.com:411
adcs://example.com:412
```
See [Direct Connect](https://en.wikipedia.org/wiki/Direct_Connect_(protocol)) and [Advanced Direct Connect](https://en.wikipedia.org/wiki/Advanced_Direct_Connect) protocols for details.

> I'll try to search a new one

Just open from global menu: `Hubs --> Public hubs`
Then sort hubs list by users count and connect to ones you like.

**Comment by tehnick** [comment]
In any case I would suggest to check work in passive mode first. And if all works fine then test active mode.

**Comment by tehnick** [comment]
BTW, after second look at you screenshot I see that you have tried to bind to specific address `192.168.*.*` and this is typical address in local network. And if this is true and DC hub which you are trying to connect is not in the same local network then you cannot use active mode, because you are behind the NAT.

**Comment by MaxD72** [comment]
ok later I'll try and I let you know...thank you so much

**Comment by MaxD72** [comment]
Ok is working properly at the moment...thank you so much again... (Y)

**Comment by MaxD72** [comment]
Last thing is possible to ask you, how can I see the HUB main chat window or can I split the main chat with utent list?
Thx

**Comment by tehnick** [comment]
> Only a thing is no working, download

If you successfully entered to HUB and see other users this does not mean that you may download file from them. Ability of searching and downloading files depends on your connection type and connection type of other users. For example, "passive user" may download files only from "active users".

But if you are behind Internet provider's NAT you do not have a choice and should use "passive mode".

Read documentation about Direct Connect protocol...

**Comment by MaxD72** [comment]
How can I discover if there is an Internet provider's NAT?
