### ISSUE TITLE
Problem with HTTP requests (hublist affected)

### ISSUE THREAD

**Issue by masscream** [eiskaltdcpp/eiskaltdcpp#435]
Hello, I have strange problem with HTTP requests in EDC. It can be something in the system settings too, because Eiskalt was working on my laptop before, then I switched from Linux Mint Cinnamon to Debian 10 Xfce and here I can't download any hublist. When it attempts to download it, it does not translate it correctly and trying to download from URL: http://dchublist.com/https://<domain of my public IP>/https://mydomain.com/https://mydomain.com/
(with the real domain ) and it fails with the error "Download failed: HTTP/1.1 414 Request-URI Too Long". Tried using https or server IP directly but it always adds this my domain URL loop. I thought it was a problem with hublists only until I tried to load a webpage from the Help menu (any). That throws this error "Unable to detect the URI-scheme of "random chars, look like coding unsupported".
I'm not sure if these errors are related but they at least look like. When eiskalt run through cmdline, the only error I can get is at the second case (Help menu webpage) and is following:
```
(exo-open:20401): Pango-WARNING **: 06:54:00.255: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.261: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.261: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.303: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.304: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.304: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.622: Invalid UTF-8 string passed to pango_layout_set_text()

(exo-open:20401): Pango-WARNING **: 06:54:00.625: Invalid UTF-8 string passed to pango_layout_set_text()
```
I run Debian Buster Xfce, Active settings with Firewall, manually forwarded ports. I tried Passive as well but does not seem to have any effect. I don't use any proxy too. Thank you for any hint.

![Screenshot_2020-05-14_07-15-59](https://user-images.githubusercontent.com/11753248/81896155-3b506d80-95b4-11ea-9f97-424d1b9b52f2.png)
![Screenshot_2020-05-14_07-16-44](https://user-images.githubusercontent.com/11753248/81896158-40152180-95b4-11ea-9a9c-61746f8f1250.png)
![Screenshot_2020-05-14_07-17-13](https://user-images.githubusercontent.com/11753248/81896162-42777b80-95b4-11ea-8516-7c889d0303cd.png)

**Comment by tehnick** [comment]
Could you try eiskaltdcpp 2.2.10+583+g17a6b034 from official Debian backports?
https://packages.debian.org/buster-backports/eiskaltdcpp
https://backports.debian.org/Instructions/

Also consider switching to EiskaltDC++ **Qt**, because GTK+ UI has unfixed bugs (segfault in Search tab, for example) and will be removed in one of next releases (after 2.4.0 or later).

**Comment by tehnick** [comment]
Also you may try remove block:
```xml
<HublistServers type="string">...</HublistServers>
```
from program's config:
```
~/.config/eiskaltdc++/DCPlusPlus.xml
```
using any text editor.

Make sure that program is finished before editing of this config.

After launching program you should see default list of available hublists.

**Comment by masscream** [comment]
Thank you. Updating the client from backports did the trick!
