### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [eiskaltdcpp/eiskaltdcpp#446]
Thank you very much for the program distributed under a free open license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82/%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8/eiskaltdc-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%BE%D0%B1%D0%BC%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9-%D1%81%D0%B5%D1%82%D0%B8-direct-connect.html).

Please do not drop the project, this is a very interesting program!

Will stable versions be published on SourceForge or here?

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.0 is released.

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.1 is released.

**Comment by mrkaban** [comment]
Thank you!
