### ISSUE TITLE
Search problems

### ISSUE THREAD

**Issue by arromdee** [eiskaltdcpp/eiskaltdcpp#448]
eiskaltdc++ 2.3.0 QT version on Mageia Linux 7.1.

-- When the result of the search is a single file shared by multiple people, the arrow on the left of the count to expand the list.of files is missing.  This is a visual problem; clicking on the nonexistent arrow still expands the list.
-- Searching does not return the copy of a file that you yourself are sharing.  Obviously you don't want to download your own file, but not being able to search files that you are sharing makes it hard to troubleshoot sharing problems.
-- My preferences were set, in Sharing/Exceptions, not to share files matching the pattern "comics.*"  I have a file in my share directory named "comics.misc".  When I right-click on my username in the hub and choose "Browse Files", it still shows me this file.  This also combines with the previous problem--since my own files are not returned by a search, I have no way to confirm that my exception syntax is correct and that the files cannot be searched.

**Comment by tehnick** [comment]
> -- When the result of the search is a single file shared by multiple people, the arrow on the left of the count to expand the list.of files is missing. This is a visual problem; clicking on the nonexistent arrow still expands the list.

This depends on chosen Qt theme. You may change Qt theme for EiskaltDC++ directly in program settings.

> -- Searching does not return the copy of a file that you yourself are sharing. Obviously you don't want to download your own file, but not being able to search files that you are sharing makes it hard to troubleshoot sharing problems.

This behavior may be changed directly in search widget: look at special combobox on left  panel before search.

> -- My preferences were set, in Sharing/Exceptions, not to share files matching the pattern "comics.*" I have a file in my share directory named "comics.misc". When I right-click on my username in the hub and choose "Browse Files", it still shows me this file.

1) File lists browser may show you cached version of file list. Try to remove files from `~/.local/share/eiskaltdc++/FileLists/`.
2) You own file list is generated asynchronously and independently from database of shared files. To make sure that specific file is not present in you file list try to restart the program after updating the list of share exceptions and after updating of share by special pushbutton.

**Comment by tehnick** [comment]
> own file list is generated asynchronously
> ...
> try to restart the program

Or you may safely delete these files and request own file list from menu:
```
~/.config/eiskaltdc++/files.xml.bz2
~/.config/eiskaltdc++/files.xml.bz2.bak
```
