### ISSUE TITLE
Unable to make (incomplete type 'class dcpp::Socket'

### ISSUE THREAD

**Issue by erokonson** [eiskaltdcpp/eiskaltdcpp#449]
Hi,
When building, cmake works fine. But when I try to make it fails directly on dyndns.cpp.o as below

make[1]: Entering directory '/home/anon/builddir'
make[2]: Entering directory '/home/anon/builddir'
Scanning dependencies of target extra
make[2]: Leaving directory '/home/anon/builddir'
make[2]: Entering directory '/home/anon/builddir'
[  1%] Building CXX object extra/CMakeFiles/extra.dir/dyndns.cpp.o
In file included from /home/anon/dcpp/ClientManager.h:21,
                 from /home/anon/extra/dyndns.cpp:19:
/home/anon/dcpp/Client.h:166:72: error: ‘dcpp::Socket::Protocol’ has not been declared
  166 | const string& hubURL, char separator, bool secure_, Socket::Protocol proto_);
      |                                                             ^~~~~~~~

/home/anon/Client.h:230:13: error: invalid use of incomplete type ‘class dcpp::Socket’
  230 |     Socket::Protocol proto;
      |             ^~~~~~~~
In file included from /home/anon/dcpp/HttpConnectionListener.h:22,
                 from /home/anon/dcpp/HttpConnection.h:24,
                 from /home/anon/extra/dyndns.h:19,
                 from /home/anon/extra/dyndns.cpp:17:
/home/anon/dcpp/forward.h:95:7: note: forward declaration of ‘class dcpp::Socket’
   95 | class Socket;
      |       ^~~~~~
make[2]: *** [extra/CMakeFiles/extra.dir/build.make:63: extra/CMakeFiles/extra.dir/dyndns.cpp.o] Error 1
make[2]: Leaving directory '/home/anon/builddir'
make[1]: *** [CMakeFiles/Makefile2:250: extra/CMakeFiles/extra.dir/all] Error 2
make[1]: Leaving directory '/home/anon/builddir'
make: *** [Makefile:130: all] Error 2

I've tried it on a new Ubuntu 20.10 install and a Slackware64-current with the same result.

**Comment by tehnick** [comment]
Use sources from git master branch, see:
https://launchpad.net/~tehnick/+archive/ubuntu/direct-connect-devel/+packages

**Comment by erokonson** [comment]
Thank you for your quick reply!
I've cloned master from github since I prefer a non-ubuntu build. I just used ubuntu to see if the problem would replicate. Am I cloning the wrong branch from github?

**Comment by tehnick** [comment]
> I just used ubuntu to see if the problem would replicate.

As you see in official PPA all packages were built successfully for all supported versions of Ubuntu. Check your configuration options...

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.0 is released.
