### ISSUE TITLE
Linux build failure – are the Boost dependencies not fully removed?

### ISSUE THREAD

**Issue by UnclePain** [eiskaltdcpp/eiskaltdcpp#450]
When I try to build eiskaltdcpp from source on my Gentoo Linux system (using the ebuild [net-p2p/eiskaltdcpp-2.2.10](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-p2p/eiskaltdcpp/eiskaltdcpp-2.2.10.ebuild)), I encounter the following problem:

> cd /var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10_build/dcpp && /usr/bin/x86_64-pc-linux-gnu-g++ -DBUILDING_DCPP -DLOCALE_DIR=\"/usr/share/locale\" -DWITH_DHT -D_DATADIR=\"/usr/share/eiskaltdcpp\" -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_REENTRANT -Ddcpp_EXPORTS -I/var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10_build -I/var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10 -I/var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10_build/dcpp   -DNDEBUG -march=znver1 -O2 -mfpmath=sse -pipe -std=c++0x -pipe -Wformat -Werror=format-security -fPIC   -fPIC -o CMakeFiles/dcpp.dir/TigerHash.cpp.o -c /var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10/dcpp/TigerHash.cpp
>
> /var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10/dcpp/TigerHash.cpp:35:10: fatal error: boost/detail/endian.hpp: No such file or directory

It seems there is a Boost dependency that cannot be found. But I saw in commit [61aae71](https://github.com/eiskaltdcpp/eiskaltdcpp/commit/5d0404d2feec0c56d830c0ce2062b68ba2afb7d0) that Boost has been completely removed. And yet the configure script checks for Boost – and it seems CMake even warns about the possible source of the problem:

> -- Found Boost: /usr/include (found version "1.74.0")  
> CMake Warning at /usr/share/cmake/Modules/FindBoost.cmake:1183 (message):
>   New Boost version may have incorrect or missing dependencies and imported
>   targets
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindBoost.cmake:1307 (_Boost_COMPONENT_DEPENDENCIES)
>   /usr/share/cmake/Modules/FindBoost.cmake:1908 (_Boost_MISSING_DEPENDENCIES)
>   CMakeLists.txt:179 (find_package)
> 
> 
> -- Found Boost: /usr/include (found version "1.74.0") found components: system

**Comment by tehnick** [comment]
Just build program from git master branch. Git tag 2.2.10 was more than 5 years ago...

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.0 is released.
