### ISSUE TITLE
Build failure with disabled Lua support

### ISSUE THREAD

**Issue by UnclePain** [eiskaltdcpp/eiskaltdcpp#451]
When I try to build eiskaltdcpp from source on my Linux system, the compile fails at this point:

> In file included from /tmp/eiskaltdcpp/dcpp/ClientManager.h:21,
>                  from /tmp/eiskaltdcpp/extra/dyndns.cpp:19:
> /tmp/eiskaltdcpp/dcpp/Client.h:166:72: error: 'dcpp::Socket::Protocol' has not been declared
>   166 |     Client(const string& hubURL, char separator, bool secure_, Socket::Protocol proto_);
>       |                                                                        ^~~~~~~~
> /tmp/eiskaltdcpp/dcpp/Client.h:230:13: error: invalid use of incomplete type 'class dcpp::Socket'
>   230 |     Socket::Protocol proto;
>       |             ^~~~~~~~

Similarly for other files as well, e. g.:
> In file included from /tmp/eiskaltdcpp/dht/KBucket.h:22,
>                  from /tmp/eiskaltdcpp/dht/BootstrapManager.h:21,
>                  from /tmp/eiskaltdcpp/dht/BootstrapManager.cpp:20

or

> In file included from /tmp/eiskaltdcpp/dcpp/typedefs.h:21,
>                  from /tmp/eiskaltdcpp/dcpp/ClientListener.h:20,
>                  from /tmp/eiskaltdcpp/dcpp/Client.h:25,
>                  from /tmp/eiskaltdcpp/dht/KBucket.h:22,
>                  from /tmp/eiskaltdcpp/dht/BootstrapManager.h:21,
>                  from /tmp/eiskaltdcpp/dht/BootstrapManager.cpp:20

I have tried the manual way according the INSTALL file, as well as the build-in-ubuntu.sh script. The only thing that I changed is deactivating Lua, MiniUPnP and Aspell:
> -DLUA_SCRIPT=OFF -DWITH_LUASCRIPTS=OFF -DUSE_MINIUPNP=OFF -DUSE_ASPELL=OFF

**Comment by tehnick** [comment]
0) Which version of EiskaltDC++ are you trying to build?
1) What is your Linux distro?
2) Attach full configuration log and full log of build to this issue please.
