### ISSUE TITLE
Fatal error in TigerHash.cpp:35:10: boost/detail/endian.hpp: No such file or directory

### ISSUE THREAD

**Issue by cerebrum** [eiskaltdcpp/eiskaltdcpp#452]
_/var/tmp/portage/net-p2p/eiskaltdcpp-2.2.10/work/eiskaltdcpp-2.2.10/dcpp/TigerHash.cpp:35:10: fatal error: boost/detail/endian.hpp: No such file or directory
   35 | #include <boost/detail/endian.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated._

The use of BOOST_*_ENDIAN and BOOST_BYTE_ORDER is deprecated. Please include <boost/predef/other/endian.h> and use BOOST_ENDIAN_*_BYTE instead.
See: https://github.com/boostorg/endian/issues/45

**Comment by tehnick** [comment]
eiskaltdcpp-2.2.10 is not supported. Build program from master branch.

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.0 is released.
