### ISSUE TITLE
[Fedora] Upload :  Send block of 320Ko and stop

### ISSUE THREAD

**Issue by Shnoulle** [eiskaltdcpp/eiskaltdcpp#455]
I have a strange issue since some week non, and really don't find hjow to fix or report …

Then : i explain here.

I update from Fedora 32 to Fedora 33 some week ago. Seems since update : my upload didn't work like before.

I have 2 user asking files, i know i'm the only one to have this files, user seems to get it bnut i see they get only 320Ko by 320ko with ~3 to 5 seconds between each part sended.

I test with `eiskaltdcpp-2.4.0-1.fc33` witn gtk or qt
I try too to downgrade to `eiskaltdcpp-2.2.11-30.20200616git2ec27a2.fc33` : strangely it seems to work one time (it upload whole file in one slot).

Here the Debug Console  restricted to one IP , i yupdate (remove last part) from TTH and CID.
```
....
```
![Capture d’écran du 2020-12-21 17-03-39](https://user-images.githubusercontent.com/1439428/102803379-73c0f100-43b8-11eb-95f0-c18e5f37b8b4.png)
![Capture d’écran du 2020-12-21 17-04-34](https://user-images.githubusercontent.com/1439428/102803384-74f21e00-43b8-11eb-8c64-0d22c5144c35.png)

**Comment by Shnoulle** [comment]
? Seems to come back : i "empty history of download" and set "Network interface" ?

**Comment by tehnick** [comment]
Try official build for Linux:
https://sourceforge.net/projects/eiskaltdcpp/files/Linux/

**Comment by Shnoulle** [comment]
Thanks @tehnick , i don't see there are AppImage … 

I start to try to reproduce on Fedora rpm (2nd time i upload without issue), if i find how to rerproduce : i try witn AppImage
