### ISSUE TITLE
Some diacritics characters are replaced by questionmarks

### ISSUE THREAD

**Issue by slrslr** [eiskaltdcpp/eiskaltdcpp#458]
Hello,
i am having [this eiskaltdcpp-qt package](https://aur.archlinux.org/packages/eiskaltdcpp-qt/) (same version) on Linux installed.
and the public chat text and the sidebar that lists connected hubs, shows questionmark signs instead of all or some czech language diacritics characters like ěščřžýáíé:

![](https://i.imgur.com/MTUPgvu.png)

If important, [here are](https://bin.disroot.org/?2f40073057d3b405#ALf95xQB92jnnF6NJPnziFkkywBK7yhHcZV56UWjKr8d) some of the operating system environment variables related to language.

What do you suggest to try?

**Comment by tehnick** [comment]
> What do you suggest to try?

1) Check encoding for this hub.
2) Check if selected font supports these characters. Try another font.

Have in mind that font settings will be applied only to new messages in chats. Program restart is not needed, you may just re-connect to hub (Ctrl+R) for test.

**Comment by tehnick** [comment]
Also please report to maintainer of that package that `boost` libraries are not needed to this program.

**Comment by slrslr** [comment]
Answers @tehnick 

1. I do not know how, [hub admin says that the hub is using win-1250 encoding](https://bin.disroot.org/?47d35f2b4c2a640d#4L4iPhhUXeb6vU82dXLv1UeXqjfkEMsUgJa2oM5WXD9E)., which i know is correct encoding to show diacritic. This issue happen in multiple hub chats and also in various hub names as seen on image below.
List of connected (and Favorited) hubs on the left and list all hubs list on right:
![](https://i.imgur.com/CgD5q5e.png)

2. Default font i had Cantarell, i tried a few others, currently i set Sans Serif (Settings/GUI/Fonts - all options set to this font and testing field in Settings menu/Font section shows diacritic correctly, app was restarted)

Yet i continue to see above shown question marks in chat and in connected hub list. In some parts of the app is shown diacritics properly, as per the image - the "Public hubs" shows it correctly.

**Comment by tehnick** [comment]
I have tested that hub and all works fine:
![Screenshot_20210117_192535](https://user-images.githubusercontent.com/441190/104849382-6b49d080-58fa-11eb-9f76-f2990480d7f1.png)

With settings:
![Screenshot_20210117_192614](https://user-images.githubusercontent.com/441190/104849391-756bcf00-58fa-11eb-86bf-ea348a5f37e8.png)
![Screenshot_20210117_192820](https://user-images.githubusercontent.com/441190/104849401-83b9eb00-58fa-11eb-9927-aee07e0c79d1.png)

**Comment by slrslr** [comment]
@tehnick Changing font to yours DejaVu Sans not helped, but when i checked that hub properties in the Favortie hub list, then i see the encoding is not yours Windows-1250, but "System default" and most of my hubs in /home/me/.config/eiskaltdc++/Favorites.xml has encoding "Czech_Czech Republic.1250" while linux encoding name should likely be "CP1250". It is likely like this happened due to me importing my old Windows ApexDC++ config. files to my current Linux config folder /home/me/.config/eiskaltdc++/

When i modified the hubs encoding in Favorite hubs tab to either Windows-1250 or UTF-8 OR i do Linux command:
sed -i "s|Czech_Czech Republic.1250|UTF-8|g" ~/.config/eiskaltdc++/Favorites.xml

and launch EiskaltDC, then i see no problems, issue is solved.

--> Should the "System default" encoding or unrecognized encoding fallback to something universal like UTF-8 automatically?

**Comment by tehnick** [comment]
Default encoding is already "UTF-8". Your case with importing settings from other DC client is very special one.

I am glad that issue is solved.
