### ISSUE TITLE
Will not pull file lists or search at all?? 

### ISSUE THREAD

**Issue by davelev74** [eiskaltdcpp/eiskaltdcpp#460]
This package is NOT working and there is NO help to be found on how to make it work

**Comment by tehnick** [comment]
No description of the problem.

**Comment by davelev74** [comment]
Maybe if there was a user help site with a few directions people would be able to use your program. RTFM but there's NO F M???
Not my fault, I was a programmer for 25 years.

**Comment by tehnick** [comment]
https://github.com/eiskaltdcpp/eiskaltdcpp#usage

Information how to choose proper type of connection is the same as in any other DC client. Passive mode should work with any type of network connection. But this mode has huge limitation: you will not be able to download files from other DC clients who also in passive mode. At least from users with old DC clients which do not have no support of NATT extension.

**Comment by davelev74** [comment]
I figured it out. Changing the connection to "Firewall wth UPnP" allowed searching to work so that's a big improvement. If I can search someones filelist that would be awesome. So far that's still not working.

**Comment by davelev74** [comment]
Thanks, turns out I had to switch it from Active to allowing it to use UpnP
Even then it wasn't working well. I managed to get the windows version of
DC++ running in Wine. It was tricky but it works much better for the most
part.
David Levinson
davelev74@gmail.com
Cell: 215.817.5198
