### ISSUE TITLE
[Core] Problem with searching on ADC hubs

### ISSUE THREAD

**Issue by bobo-j** [eiskaltdcpp/eiskaltdcpp#463]
Hello. I notice that there is a problem with the searching in all adc hubs. All results have been dropped. In dc hubs it works normally. I am using the latest version of EiskaltDC ++ 2.4.1_x86_64 on Windows 7 x64
Does anyone else have this problem or is it just me?

**Comment by Arnvidr** [comment]
I have the same problem after upgrading to the 2.4.x series. I was previously using a snapshot from 20190503, where searching worked mostly fine (although some results were sometimes dropped even then, not sure if it's possible to find out why results get dropped).

**Comment by Arnvidr** [comment]
Update: it works with 2.4.0, so it is one of the later changes that makes it behave differently. The only change I found on first look is 39ea768d7b00d4acd3b2c049f17c7edcf9dc2e97, "[Core] Decrease diff with DC++ 0.868 core.", but that seems fairly innocent.

**Comment by tehnick** [comment]
Problem confirmed for `2.4.1` release.

**Comment by tehnick** [comment]
e1717a8ed0c6813ff5f03c968ce468f7a644ebf2

**Comment by tehnick** [comment]
Thanks for a bug report!

**Comment by Arnvidr** [comment]
Works for me, cheers!

**Comment by tehnick** [comment]
EiskaltDC++ 2.4.2 is released.
