### ISSUE TITLE
Connection is denied - no logs

### ISSUE THREAD

**Issue by elvisef** [eiskaltdcpp/eiskaltdcpp#468]
Hello.

My uhub does not log anything.
My log is located at: /var/log/uhub/uhub.log. What should be permissions and owner of this file ?
For now I have: root:adm (earlier: root:root) but with no change - a file is empty

In the meantime I try to connect using EisKaltDC++ application.
It says: 1.is connecting, 2:is connected and immediately 3: disconnected.

I have one user, admin, set by sqlite plugin.
I have set only registered users login.
And I am trying t oconnect to the server using various options, active, passive etc... nothing works.
No logs in any of system log files.

![2021-04-01_13-20](https://user-images.githubusercontent.com/25976749/113286918-1f99a700-92ed-11eb-860f-eae38bf91d25.png)

What else can I check ?
I am connecting through my router which is connected to the modem.
A modem is not blocking anything. The router as well.

On the server there is a firewall, but I checked with disabled firewall, no change.
The firewall has it' uhub port enabled (1511 for now to test) - no change.

**Comment by tehnick** [comment]
Show output:
```
sudo nmap 194.59.140.167 -p 1511
```

**Comment by tehnick** [comment]
How do you launch `uhub`? As a service or as a program? I would recommend to stop `uhub` service if it is running and  launch `uhub` from command line to see its output. Do not forget to launch `uhub` from the same system user which is used for launching `uhub` as a service.

**Comment by elvisef** [comment]
> 
> 
> Show output:
> 
> ```
> sudo nmap 194.59.140.167 -p 1511
> ```
> 
> (On client side.)

![firefox_qHDcfsI4iq](https://user-images.githubusercontent.com/25976749/113503801-6b8a5d00-9534-11eb-99c2-4208181dc93e.png)

UHub is run as a service, using init.d.
Systemctl shows that everything works well.

**Comment by tehnick** [comment]
As you see in `nmap` output your attempt to connect to port 1511 was filtered. One of possible reasons for such status is enabled firewall...

**Comment by elvisef** [comment]
> 
> 
> As you see in `nmap` output your attempt to connect to port 1511 was filtered. One of possible reasons for such status is enabled firewall...

Yes, I understand. But as I wrote earlier, the firewall disabled did not change anything. Just wondering, what it would be....

![putty_v9SRsaIrwA](https://user-images.githubusercontent.com/25976749/113507616-ec088800-954b-11eb-8bf9-0a39da7419c8.png)
