### ISSUE TITLE
Own filelist shows blank

### ISSUE THREAD

**Issue by joshzirinsky** [eiskaltdcpp/eiskaltdcpp#469]
Hi,

I'm running Eiskalt 2.4.2 on macOS (Catalina). When I try to look at my own file list it opens the pop-up but there's nothing there, just the navigation arrows. There is a folder selected in preferences containing multiple files, and all the files have been hashed.

Likewise, when I try to browse another user's files, it downloads the file list but then shows up blank. I know these users to have files as I have successfully browsed their files in the recent past and successfully downloaded files from them.

This problem started about 2 weeks ago, unprompted (as far as I can tell), after several months of unproblematic use. I have restarted the programme, changed my shared folder, rebooted the computer, and reinstalled the programme, all to no effect.

<img width="1597" alt="Screenshot 2021-04-26 at 01 04 18" src="https://user-images.githubusercontent.com/49160308/116014081-5aaca300-a62b-11eb-9781-727ce8fdb2bd.png">

Thank you in advance for any assistance.

**Comment by tehnick** [comment]
Are you serious? Just move this splitter to the right...
<img width="1597" alt="116014081-5aaca300-a62b-11eb-9781-727ce8fdb2bd" src="https://user-images.githubusercontent.com/441190/116035626-fd861100-a66d-11eb-9a28-44195a279bbf.png">

**Comment by tehnick** [comment]
Program UI is very flexible: you may change size almost for all elements, amount of columns in tables, etc.
