### ISSUE TITLE
eiskaltdcpp-daemon losing server connection on reboot

### ISSUE THREAD

**Issue by cardpuncher** [eiskaltdcpp/eiskaltdcpp#514]
Hi there,

I'm running eiskaltdcpp-daemon 2.4.2 on a [FreedomBox ](https://www.olimex.com/Products/OLinuXino/Home-Server/Pioneer-FreedomBox-HSK/open-source-hardware) (with a hard disk) which itself is running Debian 12 Bookworm. Everything is fine but when the box reboots, I need to SSH to add a server again with eiskaltdcpp-cli-jsonrpc's hub.add command.

Is there a way automagically reconnect on reboot? Thanks in advance.

Just FYI:
`$ uname -a
Linux freedombox 6.1.0-22-armmp-lpae #1 SMP Debian 6.1.94-1 (2024-06-21) armv7l GNU/Linux`

**Comment by tehnick** [comment]
Hi,

You may launch eiskaltdcpp-qt and set all needed main settings (including favorites hubs, connection settings, etc.) via it, and then launch eiskaltdcpp-daemon as usual.

Or you may edit EiskaltDC++ configs in `~/.config/eiskaltdc++/` manually in any text editor. As for the automatic connection to the hubs, you need to fill `Favorites.xml` config by something like this:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Favorites>
    <Hubs>
        <Group Name="Auto-connect group (converted)" Private="0" Connect="1"/>
        <Hub Name="FlylinkDC++ hub" Connect="1" Description="FlylinkDC++" Nick="" Password="******" Server="dchub://dc.fly-server.ru" UserDescription="" Encoding="CP1251" ClientId="EiskaltDC++ V:2.4.0" ExternalIP="" OverrideId="0" UseInternetIp="0" DisableChat="0" Mode="0" SearchInterval="60" Group="Auto-connect group (converted)"/>
    </Hubs>
</Favorites>
```

Please close this issue if this is enough for you.

**Comment by cardpuncher** [comment]
Thank you, that's exactly the information I was looking for!
