### ISSUE TITLE
Separation of interface and indexing processes

### ISSUE THREAD

**Issue by Korb** [eiskaltdcpp/eiskaltdcpp#518]
Currently, when indexing a large number of files, interaction with the application is almost impossible. The response time is a minute or more. Periodically, the application displays a message asking to forcefully close it:

> EiskaltDC++.exe не отвечает. При закрытии не отвечающей программы может быть потеряна несохраненная информация.
> Закрыть программу / Ожидание отклика программы

> EiskaltDC++.exe is not responding. Unsaved information may be lost when closing an unresponsive program.
> Close program / Wait for program to respond

In this case, the Windows process manager does not display significant CPU or disk load on which indexed files, applications, or caches are located.

I propose to allow the user to set the priority for the indexing process in the range from blocking work with the application (as it is now) to not affecting user processes (that is, indexing occurs only when the computer is idle).

![2024-10-12_09-50-00](https://github.com/user-attachments/assets/d47b312a-8825-4c10-bc54-b023fa7e8398)

EiskaltDC++ 2.4.2+364ga79c4dea
Microsoft Windows 10.0.19045.5011

**Comment by tehnick** [comment]
![Screenshot_20241024_235001](https://github.com/user-attachments/assets/6aa528c2-60c0-4d21-9c5f-3fc7c048307d)
Set non-zero value here and your problem should be solved.
