### ISSUE TITLE
Char encoding within the deamon

### ISSUE THREAD

**Issue by nighter83** [eiskaltdcpp/eiskaltdcpp#71]
Hi, 

I tried to find a way to get this fixed by my own, but tbh I'm completely lost in all the code and character encoding. If I try to download a file with the daemon via the magnet.add function and the file contains umlauts like ä, ö, ü or the € char, the filename is completely messed up during/after the download. 
I was able to get the "visual" ouput fixed from the CLI, but it seems that the daemon is still interpreting the characters in a wrong way. 
I'm currently using the master branch from git (2.3.0) for the daemon and the cli revision is 20140608
LANG is set to de_DE.UTF-8 on the system. 
visual output fixed in the json cli by replacing

binmode STDOUT, ':utf8';
with
binmode STDOUT, ':encoding(iso_8859_1)';

but the file is still written with some strange characters to the disk. 

I assume it might be related to the splitMagnet function, which just handles the dn parameter as a string. As I have no clue about c++ maybe someone could point me either in the right direction, to fix this or maybe it will be fixed with a new version. 

Best regards

**Comment by nighter83** [comment]
hm no feedback since November on this issue :(
dhamp, do you have any information if this will/could be fixed quickly or point me to the right direction as it is really anoying to have files with very strange filenames laying around in the filesystem, which aren't found by any search. :/

**Comment by dhamp** [comment]
for test make request in server from curl:
curl --data-binary '{"jsonrpc": "2.0", "id": "1", "method": "magnet.add", "params" : { "magent" : "@insert_you_magnet_here@"}}' -H 'content-type: text/plain;' http://127.0.0.1:3121

if this add  download with correct filename, then something work incorrect in cli client, else something work incorrect in daemon.
also you may attach example magnet for test.

**Comment by nighter83** [comment]
Hi 

Finally I found some time to work on your request. 
So If I run the query from you on the host with the daemon installed, the filename is shown correct in the webui, which wasn't the case before. 
Output from your command: {"id": "1", "jsonrpc": "2.0", "result": 0}
The file is also donwloaded from the share, but stored with a wrong filename. instead of the test filename üppöppäpp€pp@pp (used in the magnet and shown in the webui) the file is stored with the name pppppppp@pp

for better understanding: I'm running a ssh -C from a host (A) to another host (B) where the daemon and the cli are installed (turned out to be the best option for me).
the "normal" way via calling the CLI with magnet.add results in strange filenames written to the disk and shown in the webui
If I run your command via ssh -C the filename is correctly shown in the Webui, but stored without any umlauts and € chararcter on the disk.

**Comment by nighter83** [comment]
just figured out that characters like  ' and & cuts the filename and ends it immediately

**Comment by dhamp** [comment]
please attach output:
locale -a
locale
from both hosts: A and B, if this possible or at least host B.
