### ISSUE TITLE
Icon in system tray disappear when receiving PM...

### ISSUE THREAD

**Issue by Sopor-** [eiskaltdcpp/eiskaltdcpp#72]
If i have EiskaltDC++ minimized to system try and i received a message the icon disappear and to get the window restored I was forced to run eiskaltdcpp-qt.exe for the already running process to get visible. Still no icon in system tray, but when i change to the PM window the icon was visible again.

I also notice that if i use the icon in the taskbar to minimize (or the minimize button in the right upper corner) EiskaltDC++ will show one icon in the taskbar and one in the systray, but if i minimize with the icon in systray the taskbar icon disappear.

I'm running Windows 7 with EiskaltDC++ 2.3.0 (2fc0e35)

**Comment by tehnick** [comment]
Fixed in e42c04e1. Thanks for the bug report.
