### ISSUE TITLE
seg fault and connection to daemon failed

### ISSUE THREAD

**Issue by joeandjoe** [eiskaltdcpp/eiskaltdcpp#74]
Hi, i built daemon with -DLOCAL_JSONCPP=ON on archlinux
and web gui says connection to daemon failed,
enabling -S <file> on daemon makes a segmentation fault 

could you pls advise?

**Comment by dhamp** [comment]
>i built daemon with -DLOCAL_JSONCPP=ON on archlinux
and web gui says connection to daemon failed
please attach full configure commnd for cmake && also output from pacman -Qs jsoncpp

>enabling -S on daemon makes a segmentation fault 
please attach full entered command

**Comment by joeandjoe** [comment]
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DENABLE_STACKTRACE=ON -DUSE_MINIUPNP=ON -DLOCAL_MINIUPNP=ON -DPERL_REGEX=ON -DLOCAL_BOOST=ON -DLUA_SCRIPT=ON -DWITH_LUASCRIPTS=ON -DWITH_DHT=ON -DNO_UI_DAEMON=ON -DJSONRPC_DAEMON=ON -DLOCAL_JSONCPP=ON  -DUSE_QT=OFF

i didnt have jsoncpp installed before, i just tried to rebuild daemon with this package installed, with no change
pacaur -Qs jsoncpp
local/jsoncpp-cs 1.0.0-1
    A C++ library for interacting with JSON. Newer version using CMAKE and pkgconfig


eiskaltdcpp-daemon -D -v -d -S logfile
Segmentation fault (core dumped)
eiskaltdcpp-daemon -S logfile
Segmentation fault (core dumped)

**Comment by dhamp** [comment]
if you "make magic" and build internal jsoncpp library with include dir from jsoncpp-cs package(it impossible for me), this commit fix this -- https://github.com/eiskaltdcpp/eiskaltdcpp/commit/423cd6b267966969d405495323d2024c2403b6ca.

also you may try:
1) make clean build
2) run as strace eiskaltdcpp-daemon -vD and if process make segv - post output on gist.github.com and attach link here
3) run eiskaltdcpp daemon in gdb(if eiskaltdcpp builded with -DCMAKE_BUILD_TYPE=Debug or -DCMAKE_BUILD_TYPE=RelWithDebInfo ) : gdb -ex run --args eiskaltdcpp-daemon -vD and if process make segv, run "bt full" - post output on gist.github.com and attach link here 
(more detail here - https://code.google.com/p/eiskaltdc/wiki/issue_hints_en)

**Comment by joeandjoe** [comment]
thanks for advice, but i couldnt build jsoncpp with include from jsoncpp-cs, whenever i tried it failed, 
 (but i dont really know how to do it)

if i run eiskaltdcpp-daemon without "-S" it doesnt make segv, but webui cannot connect to daemon, and i dont have any logs from it, so i dont know what is wrong,

so if i run strace eiskaltdcpp-daemon -vD  it doesnt make segv (the same would be with gdb)

**Comment by dhamp** [comment]
run: gdb -ex run --args eiskaltdcpp-daemon -vD -S logfile

**Comment by joeandjoe** [comment]
link to gist
https://gist.github.com/joeandjoe/b9bdc37d736fc567c8e4

**Comment by dhamp** [comment]
add output: eiskaltdcpp-daemon -V

**Comment by joeandjoe** [comment]
eiskaltdcpp-daemon -V
2.3.0 (437e0b2)

**Comment by dhamp** [comment]
don't reproduce on my machine. by bt crash on assign in std::string - very strange.

**Comment by joeandjoe** [comment]
can you suggest how to debug or trace the issue with http server webui "connection to daemon failed"
?
or what else can i try?

**Comment by dhamp** [comment]
for test server side(eiskaltdcpp-daemon):
1) listening port:
ss -tlnp | egrep "eiskalt|3121" - check listening port
2) receive response on jsonrpc request:
curl --data-binary '{"jsonrpc": "2.0", "id": "1", "method": "show.version"}' -H 'content-type: text/plain;' http://127.0.0.1:3121

for eiskaltdcpp-web:
1) available all needed jquery scripts (use get-jquery-scripts script)
2) allow browser for execute js on all addresess or/and file:// and 127.0.0.1

**Comment by joeandjoe** [comment]
i have tested it and the output looks fine:
LISTEN     0      128               127.0.0.1:3121                     *:*      users:(("eiskaltdcpp-dae",pid=449,fd=7))
LISTEN     0      20                        *:3000                     *:*      users:(("eiskaltdcpp-dae",pid=449,fd=3))
LISTEN     0      20                        *:3001                     *:*      users:(("eiskaltdcpp-dae",pid=449,fd=4))
curl --data-binary '{"jsonrpc": "2.0", "id": "1", "method": "show.version"}' -H 'content-type: text/plain;' http://127.0.0.1:3121
{"id":"1","jsonrpc":"2.0","result":"2.3.0 (437e0b2)"}

jquery scripts are there
ls /srv/http/eiskaltdcpp-web/jquery/
jquery.easytabs.min.js  jquery.hashchange.min.js  jquery.jsonrpc.js  jquery.min.js  jquery.plugin.js  jquery.tablesorter.min.js  jquery.timer.js
i tested in firefox, it should not be blocking js

**Comment by dhamp** [comment]
by you output: eiskaltdcpp-daemon - work correctly, but client(eiskaltdcpp-web) - may be work incorrectly.
http://www.enlightenment.org/ss/e-54c5ee1dd4ffc1.70206026.png - screen when daemon not running but client try connecting to it.

**Comment by joeandjoe** [comment]
i have tried the python http server and in firefox i get the same info: 
Connection to EiskaltDC++ daemon failed on http://127.0.0.1:3121

this is the output from python web server:
This server is just for testing, it is not secure!
Only argument is the server port, it defaults to 8000.
Stop server with ctrl-c...
Serving HTTP on 0.0.0.0 port 8000 ...
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET / HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /style.css HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.min.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.tablesorter.min.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.hashchange.min.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.easytabs.min.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.jsonrpc.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.plugin.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /jquery/jquery.timer.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /config.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /eiskaltdcpp-web.js HTTP/1.1" 200 -
192.168.95.2 - - [27/Jan/2015 22:45:39] "GET /images/eiskaltdcpp.png HTTP/1.1" 200 -

**Comment by dhamp** [comment]
if you run eiskaltdcpp-daemon && python simple web server on one machine
and open index.html in firefox on other machine(via python webserver), you need set correct address in config.js and listen eiskaltdcpp-daemon on this address ( via -L 1.2.3.4 or --ip=1.2.3.4)

if you run all on one machine, i have no idea why js script not able connected to eiskaltdcpp-daemon.

**Comment by joeandjoe** [comment]
thanks, i have the first scenario and
i had loopback address in config.js and that didnt work, i changed it to physical interface ip, started daemon with the same ip, and it works
