### ISSUE TITLE
commit be6a024 Qt/Qt5 fail build

### ISSUE THREAD

**Issue by sl1pkn07** [eiskaltdcpp/eiskaltdcpp#75]
since commit be6a024a7 fail build

    -- Configuring done
    -- Generating done
    -- Build files have been written to: /home/sl1pkn07/aplicaciones/eiskaltdcpp-git/src/build-qt5
    make: *** No rule to make target 'translations_qt'.  Stop.

greetings

**Comment by dhamp** [comment]
's|translations_qt|eiskaltdcpp-qt_tr|g'  in PKGBUILD

see -> https://aur.archlinux.org/packages/ei/eiskaltdcpp-git/PKGBUILD

**Comment by sl1pkn07** [comment]
oh men....

sorry :S
