### ISSUE TITLE
Share browser error: 536870735

### ISSUE THREAD

**Issue by MountainsOfMight** [eiskaltdcpp/eiskaltdcpp#76]
I get the following error while trying to browse file lists of users with huge shares:

"Share browser error: 536870735: Greater than maximum allowed size"

Is there any way to manually increase cache (or whatever is needed) to open and browse those file lists?
I'm using version: EiskaltDC++ 2.3.0 (8c41579)

**Comment by dhamp** [comment]
enter in hub chat /dcpps MaxFilelistSize 4096

**Comment by dhamp** [comment]
5309fd0 - increase this option by default
