### ISSUE TITLE
I found a error in Clementine "now playing" script

### ISSUE THREAD

**Issue by synaomen** [eiskaltdcpp/eiskaltdcpp#79]
On /usr/share/eiskaltdcpp/qt/qtscripts/clementine_nowplay/clementine.sh in line 86 is some short error.
It looks
for((i=1;i<(10-nrate);i++))
and must be
for((i=1;i<$((10-nrate));i++))
for right work progress bar.

**Comment by dhamp** [comment]
https://github.com/eiskaltdcpp/eiskaltdcpp/commit/f4e5200bd8a22ed1eee0303a6cadbafc963ffad2 - fix
