### ISSUE TITLE
QTScript Problem

### ISSUE THREAD

**Issue by synaomen** [eiskaltdcpp/eiskaltdcpp#80]
I will add a Vlc media Toolbar to Eiskalt, but I'm not a QTScript coder. I've use the Amarok example main.js and add more buttons (play, next.....). When i activate the Script via script manager it create the buttons (and all are clickable and start the shell scripts), but when I deactivate the script it remove only the left button. The other 5 buttons are still alive.

>Import("qt.core");
>Import("qt.gui");
>
>function shellDone(ok, msg){
> var hubMgr = new HubManager();
>  var activeHub = hubMgr.getHubObject();
>
>  msg = LinkParser.parseMagnetAlias(msg);
>
>  if (ok && (activeHub != null))
>    activeHub.sendMsg(msg);
>}
>
>function actionClicked_np(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/vlc_now_play.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>function actionClicked_next(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/next.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>function actionClicked_back(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/back.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>function actionClicked_play(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/play.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>function actionClicked_vol_up(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/up.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>function actionClicked_vol_down(){
>  var shell = new ShellCommandRunner(SCRIPTS_PATH+"vlc_media_toolbar/down.sh")
>  shell["finished(bool,QString)"].connect(shellDone);
>
>  shell.run();
>}
>
>var a = new MainWindowScript();
>a.addToolButton("Vlc_vol_high", "up", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/vol_up.png"));
>var a = new MainWindowScript();
>a.addToolButton("Vlc_vol_low", "down", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/vol_down.png"));
>var a = new MainWindowScript();
>a.addToolButton("Vlc_next", "next", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/next.png"));
>var a = new MainWindowScript();
>a.addToolButton("Vlc_play", "play", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/play.png"));
>var a = new MainWindowScript();
>a.addToolButton("Vlc_back", "back", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/back.png"));
>var a = new MainWindowScript();
>a.addToolButton("Vlc_np", "now play", new >QIcon(SCRIPTS_PATH+"vlc_media_toolbar/vlc.png"));
>
>
>MainWindow.ToolBar.Vlc_np.triggered.connect(actionClicked_np);
>MainWindow.ToolBar.Vlc_next.triggered.connect(actionClicked_next);
>MainWindow.ToolBar.Vlc_play.triggered.connect(actionClicked_play);
>MainWindow.ToolBar.Vlc_back.triggered.connect(actionClicked_back);
>MainWindow.ToolBar.Vlc_vol_up.triggered.connect(actionClicked_vol_up);
>MainWindow.ToolBar.Vlc_vol_down.triggered.connect(actionClicked_vol_down);
>
>function deinit(){
>  a.remToolButton("Vlc_np");
>  a.remToolButton("Vlc_next");
>  a.remToolButton("Vlc_play");
>  a.remToolButton("Vlc_back");
>  a.remToolButton("Vlc_vol_high");
>  a.remToolButton("Vlc_vol_low");
>}

What make I false with the deinit function?

**Comment by tka4ev** [comment]
> var a = new MainWindowScript();
need to define only once.

**Comment by tka4ev** [comment]
> var a = new MainWindowScript();
> a.addToolButton("1" ...)
> a.addToolButton("2" ...)
> a.addToolButton("3" ...)
> ....
> a.remToolButton("1");
> a.remToolButton("2");
> a.remToolButton("3");

**Comment by synaomen** [comment]
Tnx for ur help. Problem solved. On deinit it remove now all buttons.
